import { CorporateModule, ModuleBundlePreset, ModularSubscriptionConfig } from '../types/saasModules';

export const CORPORATE_MODULES: CorporateModule[] = [
  {
    id: 'organization_management',
    numericOrder: 1,
    name: 'Organization Management',
    pillar: 'Organization',
    tagline: 'Multi-entity corporate governance, branch structuring and hierarchy',
    description:
      'Foundational enterprise organization modeling. Configure multi-tier legal entities, business units, branches, departmental matrixes, designations, granular role permissions, approval chains, and document policy frameworks.',
    basePriceMonthly: 199,
    perSeatPriceMonthly: 2.0,
    subFeaturesCount: 8,
    activeOrganizationsCount: 8,
    adoptionPercentage: 100,
    iconName: 'Building2',
    featureGroups: [
      {
        groupName: 'Enterprise Setup',
        items: ['Company, Business Unit & Multi-branch setup', 'Organization structure & entity charts'],
      },
      {
        groupName: 'Governance & Access',
        items: ['Departments & Designations catalog', 'User management & multi-role provisioning', 'Role-based access controls (RBAC)', 'Multi-level approval hierarchy'],
      },
      {
        groupName: 'Policy Administration',
        items: ['Company policies & statutory documents', 'Compliance and governance guidelines'],
      },
    ],
  },
  {
    id: 'recruitment_management',
    numericOrder: 2,
    name: 'Recruitment Management',
    pillar: 'People',
    tagline: 'End-to-end ATS talent acquisition, pipeline Kanban and HR handover',
    description:
      'A completely separate, enterprise-grade talent acquisition and ATS ecosystem. Manage manpower requirements, requisitions, multi-channel job publishing, candidate database, CV parsing, 10-stage pipeline, panel interviews, evaluations, and seamless HR onboarding handover.',
    badge: 'Separate Module',
    isSeparateModule: true,
    basePriceMonthly: 299,
    perSeatPriceMonthly: 3.5,
    subFeaturesCount: 14,
    activeOrganizationsCount: 7,
    adoptionPercentage: 88,
    iconName: 'Briefcase',
    featureGroups: [
      {
        groupName: 'Demand & Requisitions',
        items: ['Manpower requirements tracking', 'Job requisitions & approvals', 'Job creation, preview & publishing'],
      },
      {
        groupName: 'Candidate Sourcing & ATS',
        items: ['Searchable candidate database & talent pools', 'Resume screening & automated semantic parsing', 'Application tracking & progressive lifecycle bar', 'Candidate scorecards & shortlisting'],
      },
      {
        groupName: 'Interview & Offers',
        items: ['Calendar interview scheduling & Google Meet', 'Structured 5-dimension interview evaluations', 'Selection & formal offer letter generation', '10-column Drag-and-drop recruitment pipeline'],
      },
      {
        groupName: 'Analytics & Onboarding',
        items: ['Recruitment analytics & sourcing ROI', 'Joining confirmation & 7-point HR onboarding handover'],
      },
    ],
  },
  {
    id: 'employee_hr_management',
    numericOrder: 3,
    name: 'Employee / HR Management',
    pillar: 'People',
    tagline: 'Total employee lifecycle, attendance, leave, performance and self-service',
    description:
      'Complete HRMS suite covering the employee master registry, digital onboarding, dynamic attendance, biometric logs, shifts, leave allowances, documentation vaults, learning and development, and offboarding workflows.',
    basePriceMonthly: 249,
    perSeatPriceMonthly: 2.5,
    subFeaturesCount: 11,
    activeOrganizationsCount: 8,
    adoptionPercentage: 100,
    iconName: 'Users',
    featureGroups: [
      {
        groupName: 'Employee Lifecycle',
        items: ['Employee master & 360 profile', 'Digital employee onboarding', 'Employee lifecycle transitions', 'Resignation, handover & exit management'],
      },
      {
        groupName: 'Time & Attendance',
        items: ['Live clock in/out & attendance logs', 'Shift scheduling & rotation', 'Leave management, balance & holiday calendar'],
      },
      {
        groupName: 'Growth & Self-Service',
        items: ['Employee documents & certificates vault', 'Training & skill management', 'Performance appraisals & OKR reviews', 'Employee self-service (ESS) portal'],
      },
    ],
  },
  {
    id: 'finance_management',
    numericOrder: 4,
    name: 'Finance Management',
    pillar: 'Finance',
    tagline: 'Unified accounting, automated payroll processing and statutory tax compliance',
    description:
      'Robust corporate financial engine. Incorporates double-entry General Ledger accounting, accounts payable/receivable, automated invoicing, GST/tax filing, multi-structure payroll execution, and statutory compliance reporting.',
    basePriceMonthly: 399,
    perSeatPriceMonthly: 4.0,
    subFeaturesCount: 22,
    activeOrganizationsCount: 6,
    adoptionPercentage: 75,
    iconName: 'DollarSign',
    featureGroups: [
      {
        groupName: 'Accounting & Finance',
        items: ['Chart of accounts & General Ledger', 'Income & expense journal entries', 'Accounts receivable & payable aging', 'Invoicing, billing & payment receipts', 'GST/VAT filing & bank reconciliation', 'Real-time Cash Flow, P&L and Balance Sheet'],
      },
      {
        groupName: 'Payroll Processing',
        items: ['Custom salary structure formulas', 'Automated payroll batch run & payslips', 'Salary deductions, loans & advances', 'Expense reimbursements & claims integration'],
      },
      {
        groupName: 'Statutory Compliance',
        items: ['Provident Fund (PF) & ESI management', 'Professional Tax (PT) computation', 'TDS deduction & statutory filing', 'Audit-ready compliance tracking reports'],
      },
    ],
  },
  {
    id: 'business_costing_center',
    numericOrder: 5,
    name: 'Business Cost Center & Costing',
    pillar: 'Finance',
    tagline: 'Strategic cost modeling, pricing margins and 1/2/3-year profitability forecasting',
    description:
      'The definitive enterprise differentiator. Maps corporate verticals to products and services, establishes granular cost estimation rubrics, automates pricing margins and break-even thresholds, and projects multi-year EBITDA and cumulative profitability.',
    badge: 'Key Differentiator',
    isKeyDifferentiator: true,
    basePriceMonthly: 499,
    perSeatPriceMonthly: 5.0,
    subFeaturesCount: 26,
    activeOrganizationsCount: 5,
    adoptionPercentage: 63,
    iconName: 'TrendingUp',
    featureGroups: [
      {
        groupName: 'Business Structure',
        items: ['Business verticals & offerings', 'Services & Product hierarchies', 'Project-based business units', 'Cost centers & Revenue centers mapping'],
      },
      {
        groupName: 'Cost Estimation Dimensions',
        items: ['Direct material & BOM costing', 'Manpower & hourly resource costing', 'Machinery, tools & equipment allocation', 'Infrastructure & workspace expenses', 'Administrative & corporate overheads', 'Sales, marketing & acquisition expenses', 'Cloud technology & licensing costs', 'Variable operational cost models'],
      },
      {
        groupName: 'Pricing & Margin Intelligence',
        items: ['Total estimated unit cost calculation', 'Strategic selling price optimization', 'Gross margin & Net margin monitoring', 'Cost-to-revenue ratio analysis', 'Break-even volume & revenue points', 'Contribution margin & profitability modeling'],
      },
      {
        groupName: 'Multi-Year Business Costing Projections',
        items: ['1-Year, 2-Year & 3-Year financial horizon estimates', 'Annual revenue ramp projections', 'Fixed vs. variable cost escalation curves', 'Headcount & market growth assumptions', 'Capex & Opex investment requirement models', 'EBITDA, Net Profit & Margin forecasting', 'Cumulative profitability & ROI timelines'],
      },
    ],
  },
  {
    id: 'sales_crm',
    numericOrder: 6,
    name: 'Sales & CRM',
    pillar: 'Business & Operations',
    tagline: 'Deal pipeline, customer intelligence, quotations and sales velocity analytics',
    description:
      'High-velocity sales pipeline and customer relationship management. Track leads from capture to close, configure visual sales stages, automate follow-ups, generate formal customer quotes and sales orders, and analyze conversion velocity.',
    basePriceMonthly: 299,
    perSeatPriceMonthly: 3.0,
    subFeaturesCount: 11,
    activeOrganizationsCount: 6,
    adoptionPercentage: 75,
    iconName: 'Target',
    featureGroups: [
      {
        groupName: 'Prospecting & Lead Gen',
        items: ['Lead capture & qualification rubrics', 'Prospect accounts & buying center personas', 'Customer contact 360 database'],
      },
      {
        groupName: 'Pipeline & Deal Execution',
        items: ['Opportunities & multi-stage sales pipeline', 'Automated follow-up reminders & tasks', 'Quotation drafting, discounts & approvals', 'Sales order generation & contract confirmation'],
      },
      {
        groupName: 'Customer Insights & Performance',
        items: ['Full interaction & purchase history', 'Quota targets & rep achievement leaderboard', 'Win-loss ratios & sales velocity analytics'],
      },
    ],
  },
  {
    id: 'project_task_management',
    numericOrder: 7,
    name: 'Project & Task Management',
    pillar: 'Business & Operations',
    tagline: 'Work orders, milestone delivery, resource allocation and project profitability',
    description:
      'Enterprise delivery operations. Manage project charters, work orders, tasks, sprints, milestones, capacity planning, billable timesheets, project cost tracking, and real-time client billing margins.',
    basePriceMonthly: 249,
    perSeatPriceMonthly: 2.5,
    subFeaturesCount: 10,
    activeOrganizationsCount: 7,
    adoptionPercentage: 88,
    iconName: 'Layers',
    featureGroups: [
      {
        groupName: 'Planning & Delivery',
        items: ['Project creation & charter templates', 'Client work orders & statement of work', 'Task boards, subtasks & Gantt milestones'],
      },
      {
        groupName: 'Resource & Time Tracking',
        items: ['Resource allocation & capacity leveling', 'Employee timesheet submission & approvals', 'Billable vs. Non-billable utilization'],
      },
      {
        groupName: 'Project Financials',
        items: ['Live project cost vs. budget tracking', 'Project profitability & gross margin', 'Delivery performance & deadline health'],
      },
    ],
  },
  {
    id: 'procurement_purchase',
    numericOrder: 8,
    name: 'Procurement & Purchase',
    pillar: 'Business & Operations',
    tagline: 'Requisition to pay, RFQ bid comparison, POs and vendor management',
    description:
      'Corporate supply chain and purchasing control. Manage internal purchase requisitions, supplier onboarding, RFQ bidding comparisons, purchase orders, Goods Received Notes (GRN), invoice 3-way matching, and approval rules.',
    basePriceMonthly: 229,
    perSeatPriceMonthly: 2.0,
    subFeaturesCount: 9,
    activeOrganizationsCount: 5,
    adoptionPercentage: 63,
    iconName: 'CreditCard',
    featureGroups: [
      {
        groupName: 'Sourcing & Vendor Relations',
        items: ['Purchase requisitions from departments', 'Vendor master registry & performance rating', 'Request for Quotation (RFQ) distribution', 'Multi-vendor quotation side-by-side comparison'],
      },
      {
        groupName: 'Orders & Receiving',
        items: ['Purchase order (PO) generation', 'Goods Received Note (GRN) warehouse intake', 'Purchase invoice 3-way matching', 'Tiered purchase threshold approvals'],
      },
    ],
  },
  {
    id: 'inventory_asset_management',
    numericOrder: 9,
    name: 'Inventory & Asset Management',
    pillar: 'Business & Operations',
    tagline: 'Item master, multi-warehouse stock movement, hardware asset lifecycle',
    description:
      'Unified physical inventory and IT asset governance. Maintain item masters, barcode SKUs, multi-warehouse transfers, asset registration, employee custody assignments, maintenance scheduling, and depreciation valuation.',
    basePriceMonthly: 249,
    perSeatPriceMonthly: 2.0,
    subFeaturesCount: 10,
    activeOrganizationsCount: 6,
    adoptionPercentage: 75,
    iconName: 'Package',
    featureGroups: [
      {
        groupName: 'Stock & Warehousing',
        items: ['Central item master & SKU catalog', 'Real-time stock level monitoring', 'Multi-warehouse locations', 'Stock movements & intra-branch transfers', 'FIFO/Weighted inventory valuation'],
      },
      {
        groupName: 'Corporate Asset Governance',
        items: ['Fixed & IT asset registration', 'Asset allocation to employees/departments', 'Routine maintenance & warranty alerts', 'Asset depreciation & disposal lifecycle'],
      },
    ],
  },
  {
    id: 'customer_service_support',
    numericOrder: 10,
    name: 'Customer Service & Support',
    pillar: 'Business & Operations',
    tagline: 'Helpdesk ticketing, omnichannel service requests and SLA resolution tracking',
    description:
      'Comprehensive customer service and incident management. Handle support tickets, client complaints, service requests, SLA timers, priority escalations, agent assignments, and customer satisfaction metrics.',
    basePriceMonthly: 199,
    perSeatPriceMonthly: 2.0,
    subFeaturesCount: 8,
    activeOrganizationsCount: 5,
    adoptionPercentage: 63,
    iconName: 'HelpCircle',
    featureGroups: [
      {
        groupName: 'Ticket & Incident Operations',
        items: ['Customer ticket intake & classification', 'Complaints & service requests triage', 'Automated SLA management & timer alerts', 'Tiered escalation rules'],
      },
      {
        groupName: 'Resolution & Analytics',
        items: ['Intelligent agent service assignment', 'Ticket resolution tracking & knowledge base', 'Customer service audit history', 'CSAT & first-response support analytics'],
      },
    ],
  },
  {
    id: 'email_management',
    numericOrder: 11,
    name: 'Email Management',
    pillar: 'Communication',
    tagline: 'Corporate inbox, customer email threads and automated email-to-task pipelines',
    description:
      'A dedicated communication module embedding corporate email directly into business workflows. Includes SMTP/IMAP sync, centralized customer and employee communication histories, template libraries, automated bulk follow-ups, and email-to-lead/ticket/task conversion.',
    badge: 'Separate Module',
    isSeparateModule: true,
    basePriceMonthly: 179,
    perSeatPriceMonthly: 1.5,
    subFeaturesCount: 12,
    activeOrganizationsCount: 8,
    adoptionPercentage: 100,
    iconName: 'Mail',
    featureGroups: [
      {
        groupName: 'Corporate Mailbox',
        items: ['Corporate email sync (Google Workspace, Office 365, IMAP)', 'Unified Inbox, Sent, Drafts, and Archive folders', 'Full threaded email communication history'],
      },
      {
        groupName: 'Customer & Employee Linking',
        items: ['Customer-wise threaded email history', 'Employee-wise internal email audit trail', 'Email attachments & enterprise document linking'],
      },
      {
        groupName: 'Automation & Templates',
        items: ['Branded enterprise email templates', 'Bulk email dispatch with personalized tokens', 'Automated sequence triggers & follow-up reminders', 'Email-to-lead, Email-to-ticket & Email-to-task conversion'],
      },
    ],
  },
  {
    id: 'chat_communication',
    numericOrder: 12,
    name: 'Chat & Communication Management',
    pillar: 'Communication',
    tagline: 'Internal teams messaging, department channels, customer live chat and audio/video',
    description:
      'Real-time communication fabric for the modern enterprise. Includes direct 1:1 employee chat, departmental and project channels, customer-facing chat, multimedia file exchange, audio/video calls, and direct task creation from messages.',
    badge: 'Separate Module',
    isSeparateModule: true,
    basePriceMonthly: 199,
    perSeatPriceMonthly: 1.5,
    subFeaturesCount: 9,
    activeOrganizationsCount: 8,
    adoptionPercentage: 100,
    iconName: 'MessageSquare',
    featureGroups: [
      {
        groupName: 'Team Collaboration',
        items: ['Internal 1:1 employee messaging', 'Departmental & Team channels', 'Project-specific workspace chat', 'Secure group conversations & announcements'],
      },
      {
        groupName: 'Customer Live Chat',
        items: ['Customer live chat widget integration', 'Customer communication logs & transcripts', 'Customer-to-agent routing'],
      },
      {
        groupName: 'Productivity & Media',
        items: ['Integrated file & media sharing', 'Instant task creation from chat messages', 'Rich notifications & message search history'],
      },
    ],
  },
  {
    id: 'document_management',
    numericOrder: 13,
    name: 'Document Management',
    pillar: 'Organization',
    tagline: 'Centralized document repository, version control, electronic approvals and expiry alerts',
    description:
      'Enterprise-grade document vault. Store, categorize, and control versions for corporate documents, contracts, employee records, purchase orders, client proposals, with e-signature sign-offs and expiry notifications.',
    basePriceMonthly: 189,
    perSeatPriceMonthly: 1.5,
    subFeaturesCount: 9,
    activeOrganizationsCount: 7,
    adoptionPercentage: 88,
    iconName: 'FileText',
    featureGroups: [
      {
        groupName: 'Document Repositories',
        items: ['Company policy & registration documents', 'Employee file folders & verification records', 'Customer contracts, master service agreements & NDAs', 'Purchase, billing & project technical deliverables'],
      },
      {
        groupName: 'Governance & Security',
        items: ['Document version control & change history', 'Digital approval workflows & sign-offs', 'Automated document expiry & renewal alerts', 'Encrypted document access permissions'],
      },
    ],
  },
  {
    id: 'kpi_performance_management',
    numericOrder: 14,
    name: 'KPI & Performance Management',
    pillar: 'Control & Intelligence',
    tagline: 'Cascading corporate targets, department OKRs and weighted performance scorecards',
    description:
      'Strategic goal setting and quantitative performance governance. Cascade high-level corporate targets down to business units, departments, and individuals. Track target achievement real-time through balanced scorecards.',
    basePriceMonthly: 219,
    perSeatPriceMonthly: 2.0,
    subFeaturesCount: 8,
    activeOrganizationsCount: 6,
    adoptionPercentage: 75,
    iconName: 'Award',
    featureGroups: [
      {
        groupName: 'Target Formulation',
        items: ['Corporate strategic targets & OKRs', 'Departmental & Business-unit specific KPIs', 'Sales & Revenue volume KPI benchmarks', 'Financial efficiency & expense control KPIs'],
      },
      {
        groupName: 'Measurement & Scorecards',
        items: ['Employee individual performance goals', 'Project delivery KPI metrics', 'Live achievement tracking against targets', 'Weighted performance appraisal scorecards'],
      },
    ],
  },
  {
    id: 'workflow_automation',
    numericOrder: 15,
    name: 'Workflow & Automation',
    pillar: 'Control & Intelligence',
    tagline: 'No-code business rules, trigger-based actions, multi-step approval chains and escalations',
    description:
      'The business process automation nervous system. Design custom multi-level approval hierarchies, automated alerts, SLA timeout escalations, rule-driven field updates, recurring schedule tasks, and automated report dispatchers.',
    basePriceMonthly: 299,
    perSeatPriceMonthly: 2.5,
    subFeaturesCount: 8,
    activeOrganizationsCount: 7,
    adoptionPercentage: 88,
    iconName: 'Sparkles',
    featureGroups: [
      {
        groupName: 'Process Automation',
        items: ['Multi-level conditional approval workflows', 'Rule-based automated triggers & field updates', 'System event notifications & webhook integrations', 'Automated timeout & SLA escalations'],
      },
      {
        groupName: 'Routine Operations',
        items: ['Automated task generation for teams', 'Scheduled recurring business activities', 'Proactive alerts & renewal reminders', 'Automated recurring report dispatch'],
      },
    ],
  },
  {
    id: 'mis_analytics_dashboard',
    numericOrder: 16,
    name: 'MIS, Analytics & Management Dashboard',
    pillar: 'Control & Intelligence',
    tagline: 'Executive CXO command centers, multi-department telemetry and business forecasting',
    description:
      'Real-time corporate business intelligence. Features role-tailored dashboards for CEO, Management, Finance, Sales, Projects, HR, Operations, and Cost Centers with custom MIS reporting and macro-trend forecasting.',
    basePriceMonthly: 349,
    perSeatPriceMonthly: 3.0,
    subFeaturesCount: 13,
    activeOrganizationsCount: 7,
    adoptionPercentage: 88,
    iconName: 'BarChart3',
    featureGroups: [
      {
        groupName: 'Executive Command Centers',
        items: ['CEO 360 overview dashboard', 'Executive Management dashboard', 'Finance & Treasury dashboard', 'Sales & Pipeline velocity dashboard'],
      },
      {
        groupName: 'Operational Dashboards',
        items: ['HR & Workforce analytics dashboard', 'Recruitment ATS telemetry dashboard', 'Project delivery & resource dashboard', 'Supply chain & Operations dashboard'],
      },
      {
        groupName: 'Cost & Profitability Telemetry',
        items: ['Cost-center expenditure dashboard', 'Product/Service profitability dashboard', 'Custom corporate MIS query builder', 'Macro business performance forecasting'],
      },
    ],
  },
  {
    id: 'ai_business_intelligence',
    numericOrder: 17,
    name: 'AI & Business Intelligence',
    pillar: 'Control & Intelligence',
    tagline: 'Predictive cost forecasting, automated narrative MIS generation and risk radar',
    description:
      'Next-generation cognitive intelligence layer. Analyzes multi-module corporate data to predict cost overruns, forecast quarterly revenue, analyze project delivery risks, uncover recruitment bottlenecks, and synthesize automated executive briefings in natural language.',
    badge: 'Next-Gen AI',
    basePriceMonthly: 449,
    perSeatPriceMonthly: 4.5,
    subFeaturesCount: 10,
    activeOrganizationsCount: 5,
    adoptionPercentage: 63,
    iconName: 'Sparkles',
    featureGroups: [
      {
        groupName: 'Predictive Intelligence',
        items: ['Machine learning cost escalation prediction', 'Quarterly & annual revenue forecasting', 'Business profitability & margin sensitivity analysis', 'Project risk & schedule slippage radar'],
      },
      {
        groupName: 'People & Sourcing AI',
        items: ['Talent acquisition velocity insights', 'Employee retention & attrition risk analytics', 'Sales pipeline conversion propensity scoring'],
      },
      {
        groupName: 'Automated Executive Briefings',
        items: ['Automated natural-language MIS report synthesis', 'Executive weekly narrative briefings', 'Conversational data queries on corporate data'],
      },
    ],
  },
];

export const MODULE_BUNDLE_PRESETS: ModuleBundlePreset[] = [
  {
    id: 'full_corporate_suite',
    name: 'Full Corporate SaaS Enterprise Suite',
    description: 'All 17 integrated modules across Organization, People, Finance, Costing, Operations, Communication & AI Intelligence.',
    targetIndustry: 'Large Enterprises, Multi-Branch Corporations & Holdings',
    badge: 'Complete Platform (17/17)',
    discountPercentage: 25,
    moduleIds: CORPORATE_MODULES.map((m) => m.id),
    recommendedMonthlyFee: 3699,
  },
  {
    id: 'hr_talent_operations',
    name: 'HR, Talent & People Operations Suite',
    description: 'Core organization structure, separate recruitment ATS, employee HRMS, documents, and corporate email & chat.',
    targetIndustry: 'Growing Organizations, Agencies & Professional Services',
    badge: '6 Core Modules',
    discountPercentage: 15,
    moduleIds: [
      'organization_management',
      'recruitment_management',
      'employee_hr_management',
      'document_management',
      'email_management',
      'chat_communication',
    ],
    recommendedMonthlyFee: 999,
  },
  {
    id: 'finance_costing_suite',
    name: 'Finance, Cost Center & Profitability Suite',
    description: 'Accounting, payroll, statutory tax, business cost centers, 1/2/3-year costing projections, and executive MIS.',
    targetIndustry: 'Financial Firms, Manufacturing & Commercial Enterprises',
    badge: 'Strategic Differentiator',
    discountPercentage: 20,
    moduleIds: [
      'organization_management',
      'finance_management',
      'business_costing_center',
      'workflow_automation',
      'mis_analytics_dashboard',
      'ai_business_intelligence',
    ],
    recommendedMonthlyFee: 1599,
  },
  {
    id: 'business_operations_crm',
    name: 'Business Operations, CRM & Delivery Suite',
    description: 'Sales CRM, project management, procurement, inventory/assets, customer support, email and team communication.',
    targetIndustry: 'Logistics, Tech Services, Retail & Field Operations',
    badge: 'Operations Powerhouse',
    discountPercentage: 18,
    moduleIds: [
      'organization_management',
      'sales_crm',
      'project_task_management',
      'procurement_purchase',
      'inventory_asset_management',
      'customer_service_support',
      'email_management',
      'chat_communication',
    ],
    recommendedMonthlyFee: 1449,
  },
];

export const INITIAL_MODULAR_SUBSCRIPTIONS: ModularSubscriptionConfig[] = [
  {
    organizationId: 'org-1',
    organizationName: 'Acme Corporation',
    planTier: 'Enterprise Suite',
    bundleName: 'All 6 Core Pillars Active',
    subscribedModuleIds: CORPORATE_MODULES.map((m) => m.id),
    monthlyBaseFee: 3699,
    monthlyTotalFee: 3699,
    seatQuotas: 500,
    billingCycle: 'Annual',
    status: 'Active',
    lastUpdated: '2025-05-15',
  },
  {
    organizationId: 'org-2',
    organizationName: 'Apex Global Corp',
    planTier: 'Enterprise Suite',
    bundleName: 'All 6 Core Pillars Active',
    subscribedModuleIds: CORPORATE_MODULES.map((m) => m.id),
    monthlyBaseFee: 3699,
    monthlyTotalFee: 3699,
    seatQuotas: 500,
    billingCycle: 'Annual',
    status: 'Active',
    lastUpdated: '2025-04-10',
  },
  {
    organizationId: 'org-3',
    organizationName: 'Nexlify Technologies',
    planTier: 'Business Pro',
    bundleName: 'Organization, People & Communication Pillars',
    subscribedModuleIds: [
      'organization_management',
      'recruitment_management',
      'employee_hr_management',
      'document_management',
      'email_management',
      'chat_communication',
    ],
    monthlyBaseFee: 999,
    monthlyTotalFee: 1199,
    seatQuotas: 250,
    billingCycle: 'Monthly',
    status: 'Active',
    lastUpdated: '2025-05-01',
  },
  {
    organizationId: 'org-4',
    organizationName: 'HyperFlow Logistics',
    planTier: 'Business Pro',
    bundleName: 'Business, Organization & Communication Pillars',
    subscribedModuleIds: [
      'organization_management',
      'sales_crm',
      'project_task_management',
      'procurement_purchase',
      'inventory_asset_management',
      'customer_service_support',
      'email_management',
      'chat_communication',
    ],
    monthlyBaseFee: 1449,
    monthlyTotalFee: 1449,
    seatQuotas: 200,
    billingCycle: 'Annual',
    status: 'Active',
    lastUpdated: '2025-03-20',
  },
  {
    organizationId: 'org-5',
    organizationName: 'Zenith BioPharm',
    planTier: 'Enterprise Suite',
    bundleName: 'Finance, Control & People Pillars',
    subscribedModuleIds: [
      'organization_management',
      'finance_management',
      'business_costing_center',
      'workflow_automation',
      'mis_analytics_dashboard',
      'ai_business_intelligence',
      'employee_hr_management',
      'recruitment_management',
    ],
    monthlyBaseFee: 2199,
    monthlyTotalFee: 2499,
    seatQuotas: 750,
    billingCycle: 'Annual',
    status: 'Active',
    lastUpdated: '2025-02-18',
  },
];
