import {
  Organization,
  User,
  Department,
  Designation,
  Employee,
  AttendanceRecord,
  ShiftSchedule,
  LeaveBalance,
  LeaveRequest,
  Holiday,
  PayrollRecord,
  JobOpening,
  Candidate,
  GoalOKR,
  PerformanceReview,
  ExpenseClaim,
  Asset,
  DocumentItem,
  TrainingCourse,
  CalendarEvent,
  NotificationItem,
  AuditLog,
} from '../types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'Acme Corp',
    slug: 'acme-corp',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    plan: 'Business',
    status: 'active',
    industry: 'Technology & Software',
    totalEmployees: 124,
    maxEmployees: 250,
    contactEmail: 'admin@acmecorp.com',
    contactPhone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://acmecorp.example.com',
    createdAt: '2024-01-15',
    billingCycle: 'monthly',
    monthlyFee: 1499,
  },
  {
    id: 'org-2',
    name: 'Global Tech',
    slug: 'global-tech',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&auto=format&fit=crop&q=80',
    plan: 'Pro',
    status: 'active',
    industry: 'Financial Services',
    totalEmployees: 48,
    maxEmployees: 100,
    contactEmail: 'contact@globaltech.io',
    contactPhone: '+1 (555) 987-6543',
    location: 'New York, NY',
    website: 'https://globaltech.example.com',
    createdAt: '2024-02-10',
    billingCycle: 'annual',
    monthlyFee: 699,
  },
  {
    id: 'org-3',
    name: 'Bright Future Media',
    slug: 'bright-future',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=100&auto=format&fit=crop&q=80',
    plan: 'Basic',
    status: 'trial',
    industry: 'Marketing & Media',
    totalEmployees: 18,
    maxEmployees: 25,
    contactEmail: 'hello@brightfuture.com',
    contactPhone: '+1 (555) 456-7890',
    location: 'Austin, TX',
    website: 'https://brightfuture.example.com',
    createdAt: '2024-05-18',
    billingCycle: 'monthly',
    monthlyFee: 299,
  },
  {
    id: 'org-4',
    name: 'NextGen Solutions',
    slug: 'nextgen-solutions',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80',
    plan: 'Enterprise',
    status: 'active',
    industry: 'Healthcare & Biotech',
    totalEmployees: 450,
    maxEmployees: 1000,
    contactEmail: 'enterprise@nextgen.com',
    contactPhone: '+1 (555) 789-0123',
    location: 'Boston, MA',
    website: 'https://nextgensolutions.example.com',
    createdAt: '2023-11-01',
    billingCycle: 'annual',
    monthlyFee: 3999,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-saas-owner',
    name: 'Alexander Wright',
    email: 'saas.owner@hrmplatform.com',
    role: 'saas_owner',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    organizationId: 'platform',
    organizationName: 'HRM Platform HQ',
    status: 'active',
    createdAt: '2023-01-01',
  },
  {
    id: 'user-org-owner',
    name: 'Sarah Jenkins',
    email: 'owner@acmecorp.com',
    role: 'org_owner',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    designation: 'Chief Executive Officer',
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'user-org-admin',
    name: 'David Vance',
    email: 'admin@acmecorp.com',
    role: 'org_admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Operations',
    designation: 'Director of Operations',
    status: 'active',
    createdAt: '2024-01-16',
  },
  {
    id: 'user-hr-admin',
    name: 'Sneha Gupta',
    email: 'hr.admin@acmecorp.com',
    role: 'hr_admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Human Resources',
    designation: 'HR Director',
    status: 'active',
    createdAt: '2024-01-20',
  },
  {
    id: 'user-hr-exec',
    name: 'Vikram Joshi',
    email: 'hr.exec@acmecorp.com',
    role: 'hr_executive',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Human Resources',
    designation: 'HR Executive',
    status: 'active',
    createdAt: '2024-02-01',
  },
  {
    id: 'user-recruiter',
    name: 'Elena Rostova',
    email: 'recruiter@acmecorp.com',
    role: 'recruiter',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Talent Acquisition',
    designation: 'Lead Technical Recruiter',
    status: 'active',
    createdAt: '2024-02-05',
  },
  {
    id: 'user-payroll-admin',
    name: 'Marcus Sterling',
    email: 'payroll@acmecorp.com',
    role: 'payroll_admin',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Finance',
    designation: 'Payroll Manager',
    status: 'active',
    createdAt: '2024-01-22',
  },
  {
    id: 'user-manager',
    name: 'Amit Verma',
    email: 'manager@acmecorp.com',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Engineering',
    designation: 'Engineering Manager',
    status: 'active',
    createdAt: '2024-01-18',
  },
  {
    id: 'user-employee',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@acmecorp.com',
    role: 'employee',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Engineering',
    designation: 'Senior Software Engineer',
    employeeId: 'EMP001',
    status: 'active',
    createdAt: '2024-01-20',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-eng', organizationId: 'org-1', name: 'Engineering', code: 'ENG', employeeCount: 54, color: '#3B82F6', headName: 'Amit Verma' },
  { id: 'dept-mkt', organizationId: 'org-1', name: 'Marketing', code: 'MKT', employeeCount: 22, color: '#EC4899', headName: 'Priya Singh' },
  { id: 'dept-fin', organizationId: 'org-1', name: 'Finance', code: 'FIN', employeeCount: 14, color: '#10B981', headName: 'Marcus Sterling' },
  { id: 'dept-hr', organizationId: 'org-1', name: 'Human Resources', code: 'HR', employeeCount: 12, color: '#8B5CF6', headName: 'Sneha Gupta' },
  { id: 'dept-sales', organizationId: 'org-1', name: 'Sales', code: 'SAL', employeeCount: 16, color: '#F59E0B', headName: 'Sandeep Yadav' },
  { id: 'dept-ops', organizationId: 'org-1', name: 'Operations', code: 'OPS', employeeCount: 6, color: '#06B6D4', headName: 'David Vance' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    organizationId: 'org-1',
    employeeId: 'EMP001',
    firstName: 'Rahul',
    lastName: 'Sharma',
    fullName: 'Rahul Sharma',
    email: 'rahul.sharma@acmecorp.com',
    personalEmail: 'rahul.sharma.dev@gmail.com',
    phone: '+1 (555) 342-1001',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    departmentId: 'dept-eng',
    designation: 'Senior Software Engineer',
    designationId: 'des-se',
    managerId: 'user-manager',
    managerName: 'Amit Verma',
    joiningDate: '2023-04-15',
    dateOfBirth: '1993-08-22',
    gender: 'Male',
    maritalStatus: 'Married',
    bloodGroup: 'O+',
    address: {
      street: '450 Mission Street, Apt 12B',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94105',
    },
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 6500,
      hra: 2200,
      allowances: 1300,
      gross: 10000,
      deductions: {
        providentFund: 650,
        professionalTax: 200,
        incomeTax: 1200,
        insurance: 150,
      },
      net: 7800,
    },
    bankDetails: {
      accountHolderName: 'Rahul Sharma',
      bankName: 'Chase Bank NA',
      accountNumber: '•••• •••• 8842',
      ifscCode: 'CHASUS33',
      branch: 'Financial District Branch',
    },
    emergencyContact: {
      name: 'Ananya Sharma',
      relationship: 'Spouse',
      phone: '+1 (555) 342-9988',
    },
  },
  {
    id: 'emp-2',
    organizationId: 'org-1',
    employeeId: 'EMP002',
    firstName: 'Priya',
    lastName: 'Singh',
    fullName: 'Priya Singh',
    email: 'priya.singh@acmecorp.com',
    personalEmail: 'priya.singh@gmail.com',
    phone: '+1 (555) 342-1002',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    departmentId: 'dept-mkt',
    designation: 'Marketing Director',
    designationId: 'des-md',
    managerId: 'user-org-owner',
    managerName: 'Sarah Jenkins',
    joiningDate: '2023-02-10',
    dateOfBirth: '1991-03-14',
    gender: 'Female',
    maritalStatus: 'Single',
    bloodGroup: 'B+',
    address: {
      street: '782 Market Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94102',
    },
    employmentType: 'Full-time',
    workLocation: 'On-site',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 7500,
      hra: 2500,
      allowances: 1500,
      gross: 11500,
      deductions: {
        providentFund: 750,
        professionalTax: 200,
        incomeTax: 1450,
        insurance: 200,
      },
      net: 8900,
    },
    bankDetails: {
      accountHolderName: 'Priya Singh',
      bankName: 'Bank of America',
      accountNumber: '•••• •••• 3145',
      ifscCode: 'BOFAUS3N',
      branch: 'Market St Branch',
    },
    emergencyContact: {
      name: 'Rajendra Singh',
      relationship: 'Father',
      phone: '+1 (555) 987-1122',
    },
  },
  {
    id: 'emp-3',
    organizationId: 'org-1',
    employeeId: 'EMP003',
    firstName: 'Amit',
    lastName: 'Kumar',
    fullName: 'Amit Kumar',
    email: 'amit.kumar@acmecorp.com',
    personalEmail: 'amit.k.fin@outlook.com',
    phone: '+1 (555) 342-1003',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    departmentId: 'dept-fin',
    designation: 'Senior Accountant',
    designationId: 'des-sa',
    managerId: 'user-payroll-admin',
    managerName: 'Marcus Sterling',
    joiningDate: '2023-06-01',
    dateOfBirth: '1990-11-28',
    gender: 'Male',
    maritalStatus: 'Married',
    bloodGroup: 'A+',
    address: {
      street: '120 Montgomery St',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94104',
    },
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 5800,
      hra: 1900,
      allowances: 1100,
      gross: 8800,
      deductions: {
        providentFund: 580,
        professionalTax: 200,
        incomeTax: 1020,
        insurance: 150,
      },
      net: 6850,
    },
    bankDetails: {
      accountHolderName: 'Amit Kumar',
      bankName: 'Wells Fargo',
      accountNumber: '•••• •••• 9921',
      ifscCode: 'WFBIUS6S',
      branch: 'Montgomery Branch',
    },
    emergencyContact: {
      name: 'Meera Kumar',
      relationship: 'Spouse',
      phone: '+1 (555) 887-2341',
    },
  },
  {
    id: 'emp-4',
    organizationId: 'org-1',
    employeeId: 'EMP004',
    firstName: 'Neha',
    lastName: 'Gupta',
    fullName: 'Neha Gupta',
    email: 'neha.gupta@acmecorp.com',
    personalEmail: 'neha.g.hr@gmail.com',
    phone: '+1 (555) 342-1004',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    departmentId: 'dept-hr',
    designation: 'HR Executive',
    designationId: 'des-hre',
    managerId: 'user-hr-admin',
    managerName: 'Sneha Gupta',
    joiningDate: '2023-09-15',
    dateOfBirth: '1995-05-19',
    gender: 'Female',
    maritalStatus: 'Single',
    bloodGroup: 'AB+',
    address: {
      street: '350 Bush Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94104',
    },
    employmentType: 'Full-time',
    workLocation: 'On-site',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 4800,
      hra: 1600,
      allowances: 800,
      gross: 7200,
      deductions: {
        providentFund: 480,
        professionalTax: 200,
        incomeTax: 720,
        insurance: 120,
      },
      net: 5680,
    },
    bankDetails: {
      accountHolderName: 'Neha Gupta',
      bankName: 'Silicon Valley Bank',
      accountNumber: '•••• •••• 4410',
      ifscCode: 'SVBUS6S',
      branch: 'Bush St Branch',
    },
    emergencyContact: {
      name: 'Sunita Gupta',
      relationship: 'Mother',
      phone: '+1 (555) 431-7782',
    },
  },
  {
    id: 'emp-5',
    organizationId: 'org-1',
    employeeId: 'EMP005',
    firstName: 'Sandeep',
    lastName: 'Yadav',
    fullName: 'Sandeep Yadav',
    email: 'sandeep.yadav@acmecorp.com',
    personalEmail: 'sandeep.yadav@yahoo.com',
    phone: '+1 (555) 342-1005',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    departmentId: 'dept-sales',
    designation: 'Sales Executive',
    designationId: 'des-se-sales',
    managerId: 'user-org-admin',
    managerName: 'David Vance',
    joiningDate: '2023-10-01',
    dateOfBirth: '1994-12-05',
    gender: 'Male',
    maritalStatus: 'Single',
    bloodGroup: 'O-',
    address: {
      street: '55 2nd Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94105',
    },
    employmentType: 'Full-time',
    workLocation: 'Remote',
    officeLocation: 'Remote USA',
    status: 'Active',
    salary: {
      basic: 5000,
      hra: 1600,
      allowances: 1000,
      gross: 7600,
      deductions: {
        providentFund: 500,
        professionalTax: 200,
        incomeTax: 800,
        insurance: 150,
      },
      net: 5950,
    },
    bankDetails: {
      accountHolderName: 'Sandeep Yadav',
      bankName: 'Chase Bank',
      accountNumber: '•••• •••• 6512',
      ifscCode: 'CHASUS33',
      branch: '2nd Street Branch',
    },
    emergencyContact: {
      name: 'Ramesh Yadav',
      relationship: 'Brother',
      phone: '+1 (555) 762-9011',
    },
  },
  {
    id: 'emp-6',
    organizationId: 'org-1',
    employeeId: 'EMP006',
    firstName: 'Sarah',
    lastName: 'Connor',
    fullName: 'Sarah Connor',
    email: 'sarah.connor@acmecorp.com',
    personalEmail: 'sarah.connor@proton.me',
    phone: '+1 (555) 342-1006',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    departmentId: 'dept-eng',
    designation: 'Frontend Lead',
    designationId: 'des-fe-lead',
    managerId: 'user-manager',
    managerName: 'Amit Verma',
    joiningDate: '2024-01-10',
    dateOfBirth: '1992-07-19',
    gender: 'Female',
    maritalStatus: 'Married',
    bloodGroup: 'A-',
    address: {
      street: '100 California Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94111',
    },
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 8000,
      hra: 2600,
      allowances: 1400,
      gross: 12000,
      deductions: {
        providentFund: 800,
        professionalTax: 200,
        incomeTax: 1600,
        insurance: 200,
      },
      net: 9200,
    },
    bankDetails: {
      accountHolderName: 'Sarah Connor',
      bankName: 'Citibank NA',
      accountNumber: '•••• •••• 1928',
      ifscCode: 'CITIUS33',
      branch: 'California St Branch',
    },
    emergencyContact: {
      name: 'John Connor',
      relationship: 'Son',
      phone: '+1 (555) 234-9988',
    },
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2024-05-20',
    clockIn: '09:02 AM',
    clockOut: '06:15 PM',
    workingHours: 8.5,
    breakHours: 1.0,
    overtimeHours: 0.5,
    status: 'Present',
    location: 'San Francisco HQ',
  },
  {
    id: 'att-2',
    organizationId: 'org-1',
    employeeId: 'emp-2',
    employeeName: 'Priya Singh',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    date: '2024-05-20',
    clockIn: '09:30 AM',
    clockOut: '06:00 PM',
    workingHours: 7.5,
    breakHours: 1.0,
    overtimeHours: 0,
    status: 'Present',
    location: 'San Francisco HQ',
  },
  {
    id: 'att-3',
    organizationId: 'org-1',
    employeeId: 'emp-3',
    employeeName: 'Amit Kumar',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    date: '2024-05-20',
    clockIn: '10:15 AM',
    clockOut: '07:00 PM',
    workingHours: 7.75,
    breakHours: 1.0,
    overtimeHours: 0,
    status: 'Late',
    location: 'San Francisco HQ',
  },
  {
    id: 'att-4',
    organizationId: 'org-1',
    employeeId: 'emp-4',
    employeeName: 'Neha Gupta',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2024-05-20',
    clockIn: '--:--',
    clockOut: '--:--',
    workingHours: 0,
    breakHours: 0,
    overtimeHours: 0,
    status: 'On Leave',
    location: '--',
  },
  {
    id: 'att-5',
    organizationId: 'org-1',
    employeeId: 'emp-5',
    employeeName: 'Sandeep Yadav',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    date: '2024-05-20',
    clockIn: '08:55 AM',
    clockOut: '05:45 PM',
    workingHours: 8.0,
    breakHours: 1.0,
    overtimeHours: 0,
    status: 'Present',
    location: 'Remote',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lev-1',
    organizationId: 'org-1',
    employeeId: 'emp-2',
    employeeCode: 'EMP002',
    employeeName: 'Priya Singh',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    leaveType: 'Casual',
    startDate: '2024-05-21',
    endDate: '2024-05-23',
    days: 3,
    reason: 'Family wedding event in hometown',
    status: 'Pending',
    appliedDate: '2024-05-18',
    approverName: 'Sarah Jenkins',
  },
  {
    id: 'lev-2',
    organizationId: 'org-1',
    employeeId: 'emp-3',
    employeeCode: 'EMP003',
    employeeName: 'Amit Kumar',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    leaveType: 'Sick',
    startDate: '2024-05-18',
    endDate: '2024-05-19',
    days: 2,
    reason: 'Viral fever and doctor advice for bed rest',
    status: 'Approved',
    appliedDate: '2024-05-17',
    approverName: 'Marcus Sterling',
    approvedOrRejectedDate: '2024-05-17',
  },
  {
    id: 'lev-3',
    organizationId: 'org-1',
    employeeId: 'emp-4',
    employeeCode: 'EMP004',
    employeeName: 'Neha Gupta',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    leaveType: 'Annual',
    startDate: '2024-05-20',
    endDate: '2024-05-24',
    days: 5,
    reason: 'Annual family vacation trip',
    status: 'Approved',
    appliedDate: '2024-05-10',
    approverName: 'Sneha Gupta',
    approvedOrRejectedDate: '2024-05-11',
  },
  {
    id: 'lev-4',
    organizationId: 'org-1',
    employeeId: 'emp-5',
    employeeCode: 'EMP005',
    employeeName: 'Sandeep Yadav',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    leaveType: 'Casual',
    startDate: '2024-05-28',
    endDate: '2024-05-29',
    days: 2,
    reason: 'Personal relocation work',
    status: 'Rejected',
    appliedDate: '2024-05-15',
    approverName: 'David Vance',
    approvedOrRejectedDate: '2024-05-16',
    rejectionReason: 'Critical client demo scheduled on those dates',
  },
];

export const INITIAL_HOLIDAYS: Holiday[] = [
  { id: 'hol-1', organizationId: 'org-1', name: 'Memorial Day', date: '2024-05-27', day: 'Monday', type: 'Public' },
  { id: 'hol-2', organizationId: 'org-1', name: 'Juneteenth National Independence Day', date: '2024-06-19', day: 'Wednesday', type: 'Public' },
  { id: 'hol-3', organizationId: 'org-1', name: 'Independence Day', date: '2024-07-04', day: 'Thursday', type: 'Public' },
  { id: 'hol-4', organizationId: 'org-1', name: 'Labor Day', date: '2024-09-02', day: 'Monday', type: 'Public' },
  { id: 'hol-5', organizationId: 'org-1', name: 'Thanksgiving Day', date: '2024-11-28', day: 'Thursday', type: 'Public' },
  { id: 'hol-6', organizationId: 'org-1', name: 'Christmas Day', date: '2024-12-25', day: 'Wednesday', type: 'Public' },
];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  {
    id: 'job-1',
    organizationId: 'org-1',
    title: 'Frontend Developer',
    department: 'Engineering',
    location: 'San Francisco / Remote',
    type: 'Full-time',
    experienceRequired: '3-5 years',
    positions: 3,
    applicationsCount: 24,
    status: 'Active',
    salaryRange: '$120,000 - $150,000',
    postedDate: '2024-05-01',
    deadline: '2024-06-15',
    description: 'We are seeking an exceptional Frontend Developer with React, TypeScript, and Tailwind CSS expertise to build next-gen SaaS interfaces.',
    requirements: ['3+ years React & TypeScript', 'Modern CSS & Design Systems', 'REST/GraphQL APIs', 'Performance optimization'],
  },
  {
    id: 'job-2',
    organizationId: 'org-1',
    title: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    location: 'San Francisco HQ',
    type: 'Full-time',
    experienceRequired: '4-7 years',
    positions: 2,
    applicationsCount: 38,
    status: 'Active',
    salaryRange: '$140,000 - $175,000',
    postedDate: '2024-04-20',
    deadline: '2024-06-01',
    description: 'Looking for a Senior Backend Developer to lead our microservices architecture and high-throughput databases.',
    requirements: ['Node.js/Go experience', 'PostgreSQL & Redis', 'Docker & Kubernetes', 'System Design & Scalability'],
  },
  {
    id: 'job-3',
    organizationId: 'org-1',
    title: 'UI/UX Product Designer',
    department: 'Design',
    location: 'Remote',
    type: 'Full-time',
    experienceRequired: '3-6 years',
    positions: 1,
    applicationsCount: 16,
    status: 'Active',
    salaryRange: '$110,000 - $140,000',
    postedDate: '2024-05-05',
    deadline: '2024-06-20',
    description: 'Design world-class enterprise SaaS interfaces with clean typography, micro-interactions, and accessible workflows.',
    requirements: ['Figma master', 'Design System creation', 'Prototyping & user research', 'SaaS product portfolio'],
  },
  {
    id: 'job-4',
    organizationId: 'org-1',
    title: 'HR Executive',
    department: 'Human Resources',
    location: 'San Francisco HQ',
    type: 'Full-time',
    experienceRequired: '2-4 years',
    positions: 1,
    applicationsCount: 12,
    status: 'Active',
    salaryRange: '$75,000 - $95,000',
    postedDate: '2024-05-10',
    deadline: '2024-06-30',
    description: 'Support onboarding, attendance management, employee relations, and employee engagement activities.',
    requirements: ['HR Generalist experience', 'Payroll & compliance knowledge', 'Excellent communication skills'],
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Aarav Patel',
    email: 'aarav.patel@email.com',
    phone: '+1 (555) 782-3344',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Stripe',
    currentRole: 'Software Engineer',
    experienceYears: 4,
    stage: 'Technical Round',
    rating: 4.8,
    appliedDate: '2024-05-08',
    expectedSalary: '$135,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Outstanding React skills and solid architecture understanding. Strong cultural fit.',
    interviews: [
      {
        id: 'int-1',
        candidateId: 'cand-1',
        candidateName: 'Aarav Patel',
        jobTitle: 'Frontend Developer',
        interviewerId: 'user-manager',
        interviewerName: 'Amit Verma',
        stage: 'Technical Coding Round',
        date: '2024-05-22',
        time: '02:00 PM',
        durationMinutes: 60,
        meetingLink: 'https://meet.google.com/xyz-hrm-test',
        status: 'Scheduled',
      }
    ],
  },
  {
    id: 'cand-2',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Maya Chen',
    email: 'maya.chen@email.com',
    phone: '+1 (555) 621-8899',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Shopify',
    currentRole: 'UI Engineer',
    experienceYears: 5,
    stage: 'Interview',
    rating: 4.5,
    appliedDate: '2024-05-11',
    expectedSalary: '$145,000',
    noticePeriod: '15 Days',
    resumeUrl: '#',
    notes: 'Strong knowledge of accessible components and Tailwind CSS.',
    interviews: [],
  },
  {
    id: 'cand-3',
    organizationId: 'org-1',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    phone: '+1 (555) 441-2390',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Uber',
    currentRole: 'Senior Backend Engineer',
    experienceYears: 6,
    stage: 'HR Round',
    rating: 4.9,
    appliedDate: '2024-05-02',
    expectedSalary: '$165,000',
    noticePeriod: 'Immediate',
    resumeUrl: '#',
    notes: 'Completed technical rounds with highest score in system architecture.',
    interviews: [],
  },
  {
    id: 'cand-4',
    organizationId: 'org-1',
    jobId: 'job-3',
    jobTitle: 'UI/UX Product Designer',
    name: 'Sophia Reynolds',
    email: 'sophia.r@designstudio.com',
    phone: '+1 (555) 883-9901',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Figma Community Creator',
    currentRole: 'Lead Product Designer',
    experienceYears: 4,
    stage: 'Shortlisted',
    rating: 4.2,
    appliedDate: '2024-05-14',
    expectedSalary: '$125,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Gorgeous portfolio of SaaS dashboards.',
    interviews: [],
  },
];

export const INITIAL_GOALS: GoalOKR[] = [
  {
    id: 'goal-1',
    organizationId: 'org-1',
    title: 'Migrate Core Services to Microservices Architecture',
    description: 'Decompose monolith APIs into scalable microservices to achieve sub-100ms P99 latency.',
    ownerId: 'emp-1',
    ownerName: 'Rahul Sharma',
    ownerAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    startDate: '2024-04-01',
    dueDate: '2024-06-30',
    progress: 75,
    status: 'In Progress',
    category: 'Department',
    keyResults: [
      { id: 'kr-1', title: 'Containerize auth and billing services', target: 100, current: 100, unit: '%' },
      { id: 'kr-2', title: 'Implement gRPC inter-service communication', target: 100, current: 80, unit: '%' },
      { id: 'kr-3', title: 'Achieve P99 API response under 100ms', target: 100, current: 45, unit: '%' },
    ],
  },
  {
    id: 'goal-2',
    organizationId: 'org-1',
    title: 'Grow Organic SaaS Signups by 40%',
    description: 'Execute new content strategy, SEO optimization, and interactive demo landing page.',
    ownerId: 'emp-2',
    ownerName: 'Priya Singh',
    ownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    startDate: '2024-04-01',
    dueDate: '2024-06-30',
    progress: 60,
    status: 'In Progress',
    category: 'Department',
    keyResults: [
      { id: 'kr-4', title: 'Publish 12 high-intent SEO articles', target: 12, current: 9, unit: 'articles' },
      { id: 'kr-5', title: 'Increase website monthly visitors to 50k', target: 50000, current: 38000, unit: 'visitors' },
      { id: 'kr-6', title: 'Generate 500 trial signups', target: 500, current: 310, unit: 'signups' },
    ],
  },
  {
    id: 'goal-3',
    organizationId: 'org-1',
    title: 'Automate Month-End Payroll Reconciliation',
    description: 'Integrate automated tax calculation engine and 1-click payslip generation.',
    ownerId: 'emp-3',
    ownerName: 'Amit Kumar',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    startDate: '2024-05-01',
    dueDate: '2024-06-15',
    progress: 90,
    status: 'In Progress',
    category: 'Department',
    keyResults: [
      { id: 'kr-7', title: 'Complete tax compliance schema update', target: 100, current: 100, unit: '%' },
      { id: 'kr-8', title: 'Reduce payroll turnaround from 3 days to 4 hours', target: 100, current: 80, unit: '%' },
    ],
  },
];

export const INITIAL_EXPENSES: ExpenseClaim[] = [
  {
    id: 'exp-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    category: 'Software',
    amount: 240,
    currency: 'USD',
    date: '2024-05-14',
    description: 'JetBrains All Products Pack annual developer license',
    project: 'Core Platform Engineering',
    status: 'Approved',
    approvedDate: '2024-05-15',
    approverName: 'Amit Verma',
  },
  {
    id: 'exp-2',
    organizationId: 'org-1',
    employeeId: 'emp-2',
    employeeName: 'Priya Singh',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Travel',
    amount: 1250,
    currency: 'USD',
    date: '2024-05-10',
    description: 'Flight and accommodation for SaaS Growth Summit Chicago',
    project: 'Q2 Marketing Campaigns',
    status: 'Reimbursed',
    approvedDate: '2024-05-12',
    approverName: 'Sarah Jenkins',
  },
  {
    id: 'exp-3',
    organizationId: 'org-1',
    employeeId: 'emp-5',
    employeeName: 'Sandeep Yadav',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    category: 'Meals',
    amount: 185,
    currency: 'USD',
    date: '2024-05-18',
    description: 'Client dinner with Enterprise Prospect procurement team',
    project: 'Enterprise Accounts',
    status: 'Pending',
    approverName: 'David Vance',
  },
];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast-1',
    organizationId: 'org-1',
    assetTag: 'AST-0941',
    name: 'Apple MacBook Pro 16" M3 Max (36GB/1TB)',
    category: 'Laptop',
    serialNumber: 'C02G8721MD6T',
    assignedToEmployeeId: 'emp-1',
    assignedToEmployeeName: 'Rahul Sharma',
    assignedDate: '2023-04-16',
    condition: 'Brand New',
    status: 'Assigned',
    purchaseDate: '2023-04-10',
    purchaseCost: 3499,
  },
  {
    id: 'ast-2',
    organizationId: 'org-1',
    assetTag: 'AST-0942',
    name: 'Dell UltraSharp 32" 4K Thunderbolt Monitor',
    category: 'Monitor',
    serialNumber: 'CN-0K7938-72872',
    assignedToEmployeeId: 'emp-1',
    assignedToEmployeeName: 'Rahul Sharma',
    assignedDate: '2023-04-16',
    condition: 'Good',
    status: 'Assigned',
    purchaseDate: '2023-04-10',
    purchaseCost: 899,
  },
  {
    id: 'ast-3',
    organizationId: 'org-1',
    assetTag: 'AST-0943',
    name: 'Apple MacBook Air 15" M2 (16GB/512GB)',
    category: 'Laptop',
    serialNumber: 'C02H9843MD7U',
    assignedToEmployeeId: 'emp-2',
    assignedToEmployeeName: 'Priya Singh',
    assignedDate: '2023-02-12',
    condition: 'Good',
    status: 'Assigned',
    purchaseDate: '2023-02-05',
    purchaseCost: 1499,
  },
  {
    id: 'ast-4',
    organizationId: 'org-1',
    assetTag: 'AST-0944',
    name: 'Logitech MX Master 3S Wireless Mouse',
    category: 'Accessory',
    serialNumber: 'LZ-889123-09',
    condition: 'Brand New',
    status: 'Available',
    purchaseDate: '2024-01-10',
    purchaseCost: 99,
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    title: 'Offer Letter - Senior Software Engineer',
    category: 'Offer Letter',
    fileType: 'PDF',
    fileSize: '1.8 MB',
    uploadedDate: '2023-04-15',
    status: 'Verified',
    downloadUrl: '#',
  },
  {
    id: 'doc-2',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    title: 'National Identity Proof / Passport Scan',
    category: 'ID Proof',
    fileType: 'PDF',
    fileSize: '3.2 MB',
    uploadedDate: '2023-04-15',
    expiryDate: '2031-10-12',
    status: 'Verified',
    downloadUrl: '#',
  },
  {
    id: 'doc-3',
    organizationId: 'org-1',
    title: 'Acme Corp Employee Handbook 2024',
    category: 'Policy',
    fileType: 'PDF',
    fileSize: '4.5 MB',
    uploadedDate: '2024-01-01',
    status: 'Verified',
    downloadUrl: '#',
  },
  {
    id: 'doc-4',
    organizationId: 'org-1',
    title: 'Comprehensive Health Insurance Policy Schedule',
    category: 'Policy',
    fileType: 'PDF',
    fileSize: '2.1 MB',
    uploadedDate: '2024-01-01',
    expiryDate: '2024-12-31',
    status: 'Verified',
    downloadUrl: '#',
  },
];

export const INITIAL_TRAINING_COURSES: TrainingCourse[] = [
  {
    id: 'trn-1',
    organizationId: 'org-1',
    title: 'Advanced React 19 & Architecture Design',
    category: 'Technical',
    description: 'Master server components, custom hooks, micro-frontends, and performance optimization.',
    instructor: 'Dan Abramov & Team',
    durationHours: 16,
    totalEnrolled: 24,
    completedCount: 18,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&auto=format&fit=crop&q=80',
    status: 'Active',
    enrolledEmployees: [
      { employeeId: 'emp-1', employeeName: 'Rahul Sharma', progress: 100, status: 'Completed', score: 98, completedDate: '2024-04-10' },
      { employeeId: 'emp-6', employeeName: 'Sarah Connor', progress: 80, status: 'In Progress' },
    ],
  },
  {
    id: 'trn-2',
    organizationId: 'org-1',
    title: 'Enterprise Information Security & SOC2 Compliance',
    category: 'Compliance',
    description: 'Mandatory annual training covering zero-trust, data confidentiality, and incident protocols.',
    instructor: 'SecOps Team',
    durationHours: 4,
    totalEnrolled: 124,
    completedCount: 110,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&auto=format&fit=crop&q=80',
    status: 'Active',
    enrolledEmployees: [
      { employeeId: 'emp-1', employeeName: 'Rahul Sharma', progress: 100, status: 'Completed', score: 100, completedDate: '2024-01-20' },
      { employeeId: 'emp-2', employeeName: 'Priya Singh', progress: 100, status: 'Completed', score: 95, completedDate: '2024-01-22' },
    ],
  },
  {
    id: 'trn-3',
    organizationId: 'org-1',
    title: 'High-Impact SaaS Product Management & Growth',
    category: 'Leadership',
    description: 'Frameworks for PLG product-led growth, cohort retention, and customer feedback loops.',
    instructor: 'Elena Rostova',
    durationHours: 12,
    totalEnrolled: 18,
    completedCount: 12,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&auto=format&fit=crop&q=80',
    status: 'Active',
    enrolledEmployees: [
      { employeeId: 'emp-2', employeeName: 'Priya Singh', progress: 65, status: 'In Progress' },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-hr-admin',
    title: 'New Leave Request',
    message: 'Priya Singh applied for 3 days Casual Leave (May 21 - May 23).',
    type: 'leave',
    isRead: false,
    timestamp: '10 minutes ago',
    actionUrl: '/leave/requests',
  },
  {
    id: 'notif-2',
    userId: 'user-hr-admin',
    title: 'Interview Scheduled',
    message: 'Technical interview scheduled for Aarav Patel (Frontend Dev) on May 22 at 2:00 PM.',
    type: 'interview',
    isRead: false,
    timestamp: '1 hour ago',
    actionUrl: '/recruitment/interviews',
  },
  {
    id: 'notif-3',
    userId: 'user-hr-admin',
    title: 'Payroll Generated for May 2024',
    message: 'Monthly payroll draft for 124 employees is ready for review and disbursement.',
    type: 'payroll',
    isRead: true,
    timestamp: 'Yesterday at 5:30 PM',
    actionUrl: '/payroll',
  },
  {
    id: 'notif-4',
    userId: 'user-employee',
    title: 'Payslip Available',
    message: 'Your payslip for April 2024 has been generated and is available for download.',
    type: 'payroll',
    isRead: false,
    timestamp: '2 days ago',
    actionUrl: '/my-payroll',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    organizationId: 'org-1',
    userId: 'user-hr-admin',
    userName: 'Sneha Gupta',
    userRole: 'HR Admin',
    action: 'APPROVED_LEAVE',
    module: 'Leave Management',
    ipAddress: '192.168.1.104',
    timestamp: '2024-05-18 14:32:10',
    status: 'Success',
    details: 'Approved 2 days Sick Leave for Amit Kumar (EMP003)',
  },
  {
    id: 'log-2',
    organizationId: 'org-1',
    userId: 'user-payroll-admin',
    userName: 'Marcus Sterling',
    userRole: 'Payroll Admin',
    action: 'PROCESS_PAYROLL_BATCH',
    module: 'Payroll',
    ipAddress: '192.168.1.188',
    timestamp: '2024-05-18 11:15:00',
    status: 'Success',
    details: 'Calculated tax deductions and generated monthly batch for 124 employees',
  },
  {
    id: 'log-3',
    organizationId: 'org-1',
    userId: 'user-recruiter',
    userName: 'Elena Rostova',
    userRole: 'Recruiter',
    action: 'MOVE_CANDIDATE_STAGE',
    module: 'Recruitment ATS',
    ipAddress: '192.168.1.45',
    timestamp: '2024-05-17 16:45:22',
    status: 'Success',
    details: 'Moved candidate Aarav Patel from Shortlisted to Technical Round',
  },
];
