import {
  Organization,
  User,
  Department,
  Designation,
  Team,
  Employee,
  AttendanceRecord,
  ShiftSchedule,
  LeaveBalance,
  LeaveRequest,
  Holiday,
  PayrollRecord,
  JobOpening,
  Candidate,
  ManpowerRequirement,
  JobRequisition,
  JobApplication,
  ResumeDocument,
  InterviewEvaluation,
  JobOffer,
  OnboardingHandover,
  GoalOKR,
  PerformanceReview,
  ExpenseClaim,
  Asset,
  DocumentItem,
  TrainingCourse,
  CalendarEvent,
  NotificationItem,
  AuditLog,
} from '../types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: 'Acme Corp',
    slug: 'acme-corp',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    plan: 'Business',
    status: 'active',
    industry: 'Technology & Software',
    totalEmployees: 124,
    maxEmployees: 250,
    contactEmail: 'admin@acmecorp.com',
    contactPhone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://acmecorp.example.com',
    createdAt: '2024-01-15',
    billingCycle: 'monthly',
    monthlyFee: 1499,
    subscribedModules: [
      'organization_management',
      'recruitment_management',
      'employee_hr_management',
      'finance_management',
      'business_costing_center',
      'sales_crm',
      'project_task_management',
      'procurement_purchase',
      'inventory_asset_management',
      'customer_service_support',
      'email_management',
      'chat_communication',
      'document_management',
      'kpi_performance_management',
      'workflow_automation',
      'mis_analytics_dashboard',
      'ai_business_intelligence',
    ],
  },
  {
    id: 'org-2',
    name: 'Global Tech',
    slug: 'global-tech',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&auto=format&fit=crop&q=80',
    plan: 'Pro',
    status: 'active',
    industry: 'Financial Services',
    totalEmployees: 48,
    maxEmployees: 100,
    contactEmail: 'contact@globaltech.io',
    contactPhone: '+1 (555) 987-6543',
    location: 'New York, NY',
    website: 'https://globaltech.example.com',
    createdAt: '2024-02-10',
    billingCycle: 'annual',
    monthlyFee: 699,
    subscribedModules: [
      'organization_management',
      'recruitment_management',
      'employee_hr_management',
      'finance_management',
      'business_costing_center',
      'sales_crm',
      'project_task_management',
      'procurement_purchase',
      'inventory_asset_management',
      'customer_service_support',
      'email_management',
      'chat_communication',
      'document_management',
      'kpi_performance_management',
      'workflow_automation',
      'mis_analytics_dashboard',
      'ai_business_intelligence',
    ],
  },
  {
    id: 'org-3',
    name: 'Bright Future Media',
    slug: 'bright-future',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=100&auto=format&fit=crop&q=80',
    plan: 'Basic',
    status: 'trial',
    industry: 'Marketing & Media',
    totalEmployees: 18,
    maxEmployees: 25,
    contactEmail: 'hello@brightfuture.com',
    contactPhone: '+1 (555) 456-7890',
    location: 'Austin, TX',
    website: 'https://brightfuture.example.com',
    createdAt: '2024-05-18',
    billingCycle: 'monthly',
    monthlyFee: 299,
    subscribedModules: [
      'organization_management',
      'recruitment_management',
      'employee_hr_management',
      'document_management',
      'email_management',
      'chat_communication',
    ],
  },
  {
    id: 'org-4',
    name: 'NextGen Solutions',
    slug: 'nextgen-solutions',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80',
    plan: 'Enterprise',
    status: 'active',
    industry: 'Healthcare & Biotech',
    totalEmployees: 450,
    maxEmployees: 1000,
    contactEmail: 'enterprise@nextgen.com',
    contactPhone: '+1 (555) 789-0123',
    location: 'Boston, MA',
    website: 'https://nextgensolutions.example.com',
    createdAt: '2023-11-01',
    billingCycle: 'annual',
    monthlyFee: 3999,
    subscribedModules: [
      'organization_management',
      'sales_crm',
      'project_task_management',
      'procurement_purchase',
      'inventory_asset_management',
      'customer_service_support',
      'email_management',
      'chat_communication',
    ],
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-saas-owner',
    name: 'Alexander Wright',
    email: 'saas.owner@hrmplatform.com',
    role: 'saas_owner',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    organizationId: 'platform',
    organizationName: 'HRM Platform HQ',
    status: 'active',
    createdAt: '2023-01-01',
  },
  {
    id: 'user-org-owner',
    name: 'Sarah Jenkins',
    email: 'owner@acmecorp.com',
    role: 'org_owner',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    designation: 'Chief Executive Officer',
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'user-org-admin',
    name: 'David Vance',
    email: 'admin@acmecorp.com',
    role: 'org_admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Operations',
    designation: 'Director of Operations',
    status: 'active',
    createdAt: '2024-01-16',
  },
  {
    id: 'user-hr-admin',
    name: 'Sneha Gupta',
    email: 'hr.admin@acmecorp.com',
    role: 'hr_admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Human Resources',
    designation: 'HR Director',
    status: 'active',
    createdAt: '2024-01-20',
  },
  {
    id: 'user-hr-exec',
    name: 'Vikram Joshi',
    email: 'hr.exec@acmecorp.com',
    role: 'hr_executive',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Human Resources',
    designation: 'HR Executive',
    status: 'active',
    createdAt: '2024-02-01',
  },
  {
    id: 'user-recruiter',
    name: 'Elena Rostova',
    email: 'recruiter@acmecorp.com',
    role: 'recruiter',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Talent Acquisition',
    designation: 'Lead Technical Recruiter',
    status: 'active',
    createdAt: '2024-02-05',
  },
  {
    id: 'user-payroll-admin',
    name: 'Marcus Sterling',
    email: 'payroll@acmecorp.com',
    role: 'payroll_admin',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Finance',
    designation: 'Payroll Manager',
    status: 'active',
    createdAt: '2024-01-22',
  },
  {
    id: 'user-manager',
    name: 'Amit Verma',
    email: 'manager@acmecorp.com',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Engineering',
    designation: 'Engineering Manager',
    status: 'active',
    createdAt: '2024-01-18',
  },
  {
    id: 'user-employee',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@acmecorp.com',
    role: 'employee',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org-1',
    organizationName: 'Acme Corp',
    departmentName: 'Engineering',
    designation: 'Senior Software Engineer',
    employeeId: 'EMP001',
    status: 'active',
    createdAt: '2024-01-20',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-eng', organizationId: 'org-1', name: 'Engineering', code: 'ENG', employeeCount: 54, color: '#3B82F6', headName: 'Amit Verma' },
  { id: 'dept-mkt', organizationId: 'org-1', name: 'Marketing', code: 'MKT', employeeCount: 22, color: '#EC4899', headName: 'Priya Singh' },
  { id: 'dept-fin', organizationId: 'org-1', name: 'Finance', code: 'FIN', employeeCount: 14, color: '#10B981', headName: 'Marcus Sterling' },
  { id: 'dept-hr', organizationId: 'org-1', name: 'Human Resources', code: 'HR', employeeCount: 12, color: '#8B5CF6', headName: 'Sneha Gupta' },
  { id: 'dept-sales', organizationId: 'org-1', name: 'Sales', code: 'SAL', employeeCount: 16, color: '#F59E0B', headName: 'Sandeep Yadav' },
  { id: 'dept-ops', organizationId: 'org-1', name: 'Operations', code: 'OPS', employeeCount: 6, color: '#06B6D4', headName: 'David Vance' },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    organizationId: 'org-1',
    name: 'Frontend Architecture Core',
    departmentId: 'dept-eng',
    department: 'Engineering',
    leadName: 'Sarah Connor',
    leadRole: 'Frontend Lead',
    leadEmployeeId: 'emp-6',
    memberCount: 8,
    memberIds: ['emp-1', 'emp-6'],
    color: '#3B82F6',
    description: 'Owns UI architecture, design systems, and cross-browser performance.',
    createdAt: '2024-01-20',
  },
  {
    id: 'team-2',
    organizationId: 'org-1',
    name: 'Cloud & DevOps Infrastructure',
    departmentId: 'dept-eng',
    department: 'Engineering',
    leadName: 'Amit Verma',
    leadRole: 'Engineering Manager',
    leadEmployeeId: 'user-manager',
    memberCount: 6,
    memberIds: ['emp-1'],
    color: '#6366F1',
    description: 'CI/CD pipelines, cloud infrastructure reliability, and platform security.',
    createdAt: '2024-01-22',
  },
  {
    id: 'team-3',
    organizationId: 'org-1',
    name: 'Growth & Demand Generation',
    departmentId: 'dept-mkt',
    department: 'Marketing',
    leadName: 'Priya Singh',
    leadRole: 'Marketing Director',
    leadEmployeeId: 'emp-2',
    memberCount: 7,
    memberIds: ['emp-2'],
    color: '#10B981',
    description: 'Demand gen campaigns, SEO, paid media, and brand awareness initiatives.',
    createdAt: '2024-02-01',
  },
  {
    id: 'team-4',
    organizationId: 'org-1',
    name: 'Enterprise Accounts',
    departmentId: 'dept-sales',
    department: 'Sales',
    leadName: 'Sandeep Yadav',
    leadRole: 'Sales Executive',
    leadEmployeeId: 'emp-5',
    memberCount: 11,
    memberIds: ['emp-5'],
    color: '#F59E0B',
    description: 'Manages enterprise B2B pipeline, key account relationships, and deal closures.',
    createdAt: '2024-02-10',
  },
  {
    id: 'team-5',
    organizationId: 'org-1',
    name: 'People Operations & Culture',
    departmentId: 'dept-hr',
    department: 'Human Resources',
    leadName: 'Neha Gupta',
    leadRole: 'HR Executive',
    leadEmployeeId: 'emp-4',
    memberCount: 5,
    memberIds: ['emp-4'],
    color: '#8B5CF6',
    description: 'Employee engagement, HR policies, onboarding workflows, and culture programs.',
    createdAt: '2024-02-15',
  },
  {
    id: 'team-6',
    organizationId: 'org-1',
    name: 'Financial Controls & Reporting',
    departmentId: 'dept-fin',
    department: 'Finance',
    leadName: 'Amit Kumar',
    leadRole: 'Senior Accountant',
    leadEmployeeId: 'emp-3',
    memberCount: 4,
    memberIds: ['emp-3'],
    color: '#06B6D4',
    description: 'Budget tracking, financial forecasting, compliance audits, and ledger reporting.',
    createdAt: '2024-03-01',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    organizationId: 'org-1',
    employeeId: 'EMP001',
    firstName: 'Rahul',
    lastName: 'Sharma',
    fullName: 'Rahul Sharma',
    email: 'rahul.sharma@acmecorp.com',
    personalEmail: 'rahul.sharma.dev@gmail.com',
    phone: '+1 (555) 342-1001',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    departmentId: 'dept-eng',
    designation: 'Senior Software Engineer',
    designationId: 'des-se',
    managerId: 'user-manager',
    managerName: 'Amit Verma',
    joiningDate: '2023-04-15',
    dateOfBirth: '1993-08-22',
    gender: 'Male',
    maritalStatus: 'Married',
    bloodGroup: 'O+',
    address: {
      street: '450 Mission Street, Apt 12B',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94105',
    },
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 6500,
      hra: 2200,
      allowances: 1300,
      gross: 10000,
      deductions: {
        providentFund: 650,
        professionalTax: 200,
        incomeTax: 1200,
        insurance: 150,
      },
      net: 7800,
    },
    bankDetails: {
      accountHolderName: 'Rahul Sharma',
      bankName: 'Chase Bank NA',
      accountNumber: '•••• •••• 8842',
      ifscCode: 'CHASUS33',
      branch: 'Financial District Branch',
    },
    emergencyContact: {
      name: 'Ananya Sharma',
      relationship: 'Spouse',
      phone: '+1 (555) 342-9988',
    },
  },
  {
    id: 'emp-2',
    organizationId: 'org-1',
    employeeId: 'EMP002',
    firstName: 'Priya',
    lastName: 'Singh',
    fullName: 'Priya Singh',
    email: 'priya.singh@acmecorp.com',
    personalEmail: 'priya.singh@gmail.com',
    phone: '+1 (555) 342-1002',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    departmentId: 'dept-mkt',
    designation: 'Marketing Director',
    designationId: 'des-md',
    managerId: 'user-org-owner',
    managerName: 'Sarah Jenkins',
    joiningDate: '2023-02-10',
    dateOfBirth: '1991-03-14',
    gender: 'Female',
    maritalStatus: 'Single',
    bloodGroup: 'B+',
    address: {
      street: '782 Market Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94102',
    },
    employmentType: 'Full-time',
    workLocation: 'On-site',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 7500,
      hra: 2500,
      allowances: 1500,
      gross: 11500,
      deductions: {
        providentFund: 750,
        professionalTax: 200,
        incomeTax: 1450,
        insurance: 200,
      },
      net: 8900,
    },
    bankDetails: {
      accountHolderName: 'Priya Singh',
      bankName: 'Bank of America',
      accountNumber: '•••• •••• 3145',
      ifscCode: 'BOFAUS3N',
      branch: 'Market St Branch',
    },
    emergencyContact: {
      name: 'Rajendra Singh',
      relationship: 'Father',
      phone: '+1 (555) 987-1122',
    },
  },
  {
    id: 'emp-3',
    organizationId: 'org-1',
    employeeId: 'EMP003',
    firstName: 'Amit',
    lastName: 'Kumar',
    fullName: 'Amit Kumar',
    email: 'amit.kumar@acmecorp.com',
    personalEmail: 'amit.k.fin@outlook.com',
    phone: '+1 (555) 342-1003',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    departmentId: 'dept-fin',
    designation: 'Senior Accountant',
    designationId: 'des-sa',
    managerId: 'user-payroll-admin',
    managerName: 'Marcus Sterling',
    joiningDate: '2023-06-01',
    dateOfBirth: '1990-11-28',
    gender: 'Male',
    maritalStatus: 'Married',
    bloodGroup: 'A+',
    address: {
      street: '120 Montgomery St',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94104',
    },
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 5800,
      hra: 1900,
      allowances: 1100,
      gross: 8800,
      deductions: {
        providentFund: 580,
        professionalTax: 200,
        incomeTax: 1020,
        insurance: 150,
      },
      net: 6850,
    },
    bankDetails: {
      accountHolderName: 'Amit Kumar',
      bankName: 'Wells Fargo',
      accountNumber: '•••• •••• 9921',
      ifscCode: 'WFBIUS6S',
      branch: 'Montgomery Branch',
    },
    emergencyContact: {
      name: 'Meera Kumar',
      relationship: 'Spouse',
      phone: '+1 (555) 887-2341',
    },
  },
  {
    id: 'emp-4',
    organizationId: 'org-1',
    employeeId: 'EMP004',
    firstName: 'Neha',
    lastName: 'Gupta',
    fullName: 'Neha Gupta',
    email: 'neha.gupta@acmecorp.com',
    personalEmail: 'neha.g.hr@gmail.com',
    phone: '+1 (555) 342-1004',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    departmentId: 'dept-hr',
    designation: 'HR Executive',
    designationId: 'des-hre',
    managerId: 'user-hr-admin',
    managerName: 'Sneha Gupta',
    joiningDate: '2023-09-15',
    dateOfBirth: '1995-05-19',
    gender: 'Female',
    maritalStatus: 'Single',
    bloodGroup: 'AB+',
    address: {
      street: '350 Bush Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94104',
    },
    employmentType: 'Full-time',
    workLocation: 'On-site',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 4800,
      hra: 1600,
      allowances: 800,
      gross: 7200,
      deductions: {
        providentFund: 480,
        professionalTax: 200,
        incomeTax: 720,
        insurance: 120,
      },
      net: 5680,
    },
    bankDetails: {
      accountHolderName: 'Neha Gupta',
      bankName: 'Silicon Valley Bank',
      accountNumber: '•••• •••• 4410',
      ifscCode: 'SVBUS6S',
      branch: 'Bush St Branch',
    },
    emergencyContact: {
      name: 'Sunita Gupta',
      relationship: 'Mother',
      phone: '+1 (555) 431-7782',
    },
  },
  {
    id: 'emp-5',
    organizationId: 'org-1',
    employeeId: 'EMP005',
    firstName: 'Sandeep',
    lastName: 'Yadav',
    fullName: 'Sandeep Yadav',
    email: 'sandeep.yadav@acmecorp.com',
    personalEmail: 'sandeep.yadav@yahoo.com',
    phone: '+1 (555) 342-1005',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    departmentId: 'dept-sales',
    designation: 'Sales Executive',
    designationId: 'des-se-sales',
    managerId: 'user-org-admin',
    managerName: 'David Vance',
    joiningDate: '2023-10-01',
    dateOfBirth: '1994-12-05',
    gender: 'Male',
    maritalStatus: 'Single',
    bloodGroup: 'O-',
    address: {
      street: '55 2nd Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94105',
    },
    employmentType: 'Full-time',
    workLocation: 'Remote',
    officeLocation: 'Remote USA',
    status: 'Active',
    salary: {
      basic: 5000,
      hra: 1600,
      allowances: 1000,
      gross: 7600,
      deductions: {
        providentFund: 500,
        professionalTax: 200,
        incomeTax: 800,
        insurance: 150,
      },
      net: 5950,
    },
    bankDetails: {
      accountHolderName: 'Sandeep Yadav',
      bankName: 'Chase Bank',
      accountNumber: '•••• •••• 6512',
      ifscCode: 'CHASUS33',
      branch: '2nd Street Branch',
    },
    emergencyContact: {
      name: 'Ramesh Yadav',
      relationship: 'Brother',
      phone: '+1 (555) 762-9011',
    },
  },
  {
    id: 'emp-6',
    organizationId: 'org-1',
    employeeId: 'EMP006',
    firstName: 'Sarah',
    lastName: 'Connor',
    fullName: 'Sarah Connor',
    email: 'sarah.connor@acmecorp.com',
    personalEmail: 'sarah.connor@proton.me',
    phone: '+1 (555) 342-1006',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    departmentId: 'dept-eng',
    designation: 'Frontend Lead',
    designationId: 'des-fe-lead',
    managerId: 'user-manager',
    managerName: 'Amit Verma',
    joiningDate: '2024-01-10',
    dateOfBirth: '1992-07-19',
    gender: 'Female',
    maritalStatus: 'Married',
    bloodGroup: 'A-',
    address: {
      street: '100 California Street',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94111',
    },
    employmentType: 'Full-time',
    workLocation: 'Hybrid',
    officeLocation: 'San Francisco HQ',
    status: 'Active',
    salary: {
      basic: 8000,
      hra: 2600,
      allowances: 1400,
      gross: 12000,
      deductions: {
        providentFund: 800,
        professionalTax: 200,
        incomeTax: 1600,
        insurance: 200,
      },
      net: 9200,
    },
    bankDetails: {
      accountHolderName: 'Sarah Connor',
      bankName: 'Citibank NA',
      accountNumber: '•••• •••• 1928',
      ifscCode: 'CITIUS33',
      branch: 'California St Branch',
    },
    emergencyContact: {
      name: 'John Connor',
      relationship: 'Son',
      phone: '+1 (555) 234-9988',
    },
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2024-05-20',
    clockIn: '09:02 AM',
    clockOut: '06:15 PM',
    workingHours: 8.5,
    breakHours: 1.0,
    overtimeHours: 0.5,
    status: 'Present',
    location: 'San Francisco HQ',
  },
  {
    id: 'att-2',
    organizationId: 'org-1',
    employeeId: 'emp-2',
    employeeName: 'Priya Singh',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    date: '2024-05-20',
    clockIn: '09:30 AM',
    clockOut: '06:00 PM',
    workingHours: 7.5,
    breakHours: 1.0,
    overtimeHours: 0,
    status: 'Present',
    location: 'San Francisco HQ',
  },
  {
    id: 'att-3',
    organizationId: 'org-1',
    employeeId: 'emp-3',
    employeeName: 'Amit Kumar',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    date: '2024-05-20',
    clockIn: '10:15 AM',
    clockOut: '07:00 PM',
    workingHours: 7.75,
    breakHours: 1.0,
    overtimeHours: 0,
    status: 'Late',
    location: 'San Francisco HQ',
  },
  {
    id: 'att-4',
    organizationId: 'org-1',
    employeeId: 'emp-4',
    employeeName: 'Neha Gupta',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2024-05-20',
    clockIn: '--:--',
    clockOut: '--:--',
    workingHours: 0,
    breakHours: 0,
    overtimeHours: 0,
    status: 'On Leave',
    location: '--',
  },
  {
    id: 'att-5',
    organizationId: 'org-1',
    employeeId: 'emp-5',
    employeeName: 'Sandeep Yadav',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    date: '2024-05-20',
    clockIn: '08:55 AM',
    clockOut: '05:45 PM',
    workingHours: 8.0,
    breakHours: 1.0,
    overtimeHours: 0,
    status: 'Present',
    location: 'Remote',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lev-1',
    organizationId: 'org-1',
    employeeId: 'emp-2',
    employeeCode: 'EMP002',
    employeeName: 'Priya Singh',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    leaveType: 'Casual',
    startDate: '2024-05-21',
    endDate: '2024-05-23',
    days: 3,
    reason: 'Family wedding event in hometown',
    status: 'Pending',
    appliedDate: '2024-05-18',
    approverName: 'Sarah Jenkins',
  },
  {
    id: 'lev-2',
    organizationId: 'org-1',
    employeeId: 'emp-3',
    employeeCode: 'EMP003',
    employeeName: 'Amit Kumar',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    leaveType: 'Sick',
    startDate: '2024-05-18',
    endDate: '2024-05-19',
    days: 2,
    reason: 'Viral fever and doctor advice for bed rest',
    status: 'Approved',
    appliedDate: '2024-05-17',
    approverName: 'Marcus Sterling',
    approvedOrRejectedDate: '2024-05-17',
  },
  {
    id: 'lev-3',
    organizationId: 'org-1',
    employeeId: 'emp-4',
    employeeCode: 'EMP004',
    employeeName: 'Neha Gupta',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    leaveType: 'Annual',
    startDate: '2024-05-20',
    endDate: '2024-05-24',
    days: 5,
    reason: 'Annual family vacation trip',
    status: 'Approved',
    appliedDate: '2024-05-10',
    approverName: 'Sneha Gupta',
    approvedOrRejectedDate: '2024-05-11',
  },
  {
    id: 'lev-4',
    organizationId: 'org-1',
    employeeId: 'emp-5',
    employeeCode: 'EMP005',
    employeeName: 'Sandeep Yadav',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    leaveType: 'Casual',
    startDate: '2024-05-28',
    endDate: '2024-05-29',
    days: 2,
    reason: 'Personal relocation work',
    status: 'Rejected',
    appliedDate: '2024-05-15',
    approverName: 'David Vance',
    approvedOrRejectedDate: '2024-05-16',
    rejectionReason: 'Critical client demo scheduled on those dates',
  },
];

export const INITIAL_HOLIDAYS: Holiday[] = [
  { id: 'hol-1', organizationId: 'org-1', name: 'Memorial Day', date: '2024-05-27', day: 'Monday', type: 'Public' },
  { id: 'hol-2', organizationId: 'org-1', name: 'Juneteenth National Independence Day', date: '2024-06-19', day: 'Wednesday', type: 'Public' },
  { id: 'hol-3', organizationId: 'org-1', name: 'Independence Day', date: '2024-07-04', day: 'Thursday', type: 'Public' },
  { id: 'hol-4', organizationId: 'org-1', name: 'Labor Day', date: '2024-09-02', day: 'Monday', type: 'Public' },
  { id: 'hol-5', organizationId: 'org-1', name: 'Thanksgiving Day', date: '2024-11-28', day: 'Thursday', type: 'Public' },
  { id: 'hol-6', organizationId: 'org-1', name: 'Christmas Day', date: '2024-12-25', day: 'Wednesday', type: 'Public' },
];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  {
    id: 'job-1',
    organizationId: 'org-1',
    title: 'Frontend Developer',
    department: 'Engineering',
    location: 'San Francisco / Remote',
    type: 'Full-time',
    experienceRequired: '3-5 years',
    positions: 3,
    applicationsCount: 24,
    status: 'Active',
    salaryRange: '$120,000 - $150,000',
    postedDate: '2024-05-01',
    deadline: '2024-06-15',
    description: 'We are seeking an exceptional Frontend Developer with React, TypeScript, and Tailwind CSS expertise to build next-gen SaaS interfaces.',
    requirements: ['3+ years React & TypeScript', 'Modern CSS & Design Systems', 'REST/GraphQL APIs', 'Performance optimization'],
  },
  {
    id: 'job-2',
    organizationId: 'org-1',
    title: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    location: 'San Francisco HQ',
    type: 'Full-time',
    experienceRequired: '4-7 years',
    positions: 2,
    applicationsCount: 38,
    status: 'Active',
    salaryRange: '$140,000 - $175,000',
    postedDate: '2024-04-20',
    deadline: '2024-06-01',
    description: 'Looking for a Senior Backend Developer to lead our microservices architecture and high-throughput databases.',
    requirements: ['Node.js/Go experience', 'PostgreSQL & Redis', 'Docker & Kubernetes', 'System Design & Scalability'],
  },
  {
    id: 'job-3',
    organizationId: 'org-1',
    title: 'UI/UX Product Designer',
    department: 'Design',
    location: 'Remote',
    type: 'Full-time',
    experienceRequired: '3-6 years',
    positions: 1,
    applicationsCount: 16,
    status: 'Active',
    salaryRange: '$110,000 - $140,000',
    postedDate: '2024-05-05',
    deadline: '2024-06-20',
    description: 'Design world-class enterprise SaaS interfaces with clean typography, micro-interactions, and accessible workflows.',
    requirements: ['Figma master', 'Design System creation', 'Prototyping & user research', 'SaaS product portfolio'],
  },
  {
    id: 'job-4',
    organizationId: 'org-1',
    title: 'HR Executive',
    department: 'Human Resources',
    location: 'San Francisco HQ',
    type: 'Full-time',
    experienceRequired: '2-4 years',
    positions: 1,
    applicationsCount: 12,
    status: 'Active',
    salaryRange: '$75,000 - $95,000',
    postedDate: '2024-05-10',
    deadline: '2024-06-30',
    description: 'Support onboarding, attendance management, employee relations, and employee engagement activities.',
    requirements: ['HR Generalist experience', 'Payroll & compliance knowledge', 'Excellent communication skills'],
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Aarav Patel',
    email: 'aarav.patel@email.com',
    phone: '+1 (555) 782-3344',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Stripe',
    currentRole: 'Software Engineer',
    experienceYears: 4,
    stage: 'Technical Round',
    rating: 4.8,
    appliedDate: '2024-05-08',
    expectedSalary: '$135,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Outstanding React skills and solid architecture understanding. Strong cultural fit.',
    location: 'San Francisco, CA',
    source: 'LinkedIn',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux Toolkit'],
    education: 'B.S. in Computer Science, UC Berkeley',
    recruiterName: 'Elena Rostova',
    priority: 'High',
    talentPool: false,
    status: 'Active',
    screeningScore: 92,
    screeningStatus: 'Passed',
    interviews: [
      {
        id: 'int-1',
        candidateId: 'cand-1',
        candidateName: 'Aarav Patel',
        jobTitle: 'Frontend Developer',
        interviewerId: 'user-manager',
        interviewerName: 'Amit Verma',
        stage: 'Technical Coding Round',
        date: '2024-05-22',
        time: '02:00 PM',
        durationMinutes: 60,
        meetingLink: 'https://meet.google.com/xyz-hrm-test',
        status: 'Scheduled',
      }
    ],
  },
  {
    id: 'cand-2',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Maya Chen',
    email: 'maya.chen@email.com',
    phone: '+1 (555) 621-8899',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Shopify',
    currentRole: 'UI Engineer',
    experienceYears: 5,
    stage: 'Interview',
    rating: 4.5,
    appliedDate: '2024-05-11',
    expectedSalary: '$145,000',
    noticePeriod: '15 Days',
    resumeUrl: '#',
    notes: 'Strong knowledge of accessible components and Tailwind CSS.',
    location: 'Remote, US',
    source: 'Career Page',
    skills: ['React', 'Accessibility (a11y)', 'Design Systems', 'GraphQL', 'Jest'],
    education: 'M.S. in Software Engineering, University of Washington',
    recruiterName: 'Elena Rostova',
    priority: 'High',
    talentPool: false,
    status: 'Active',
    screeningScore: 88,
    screeningStatus: 'Passed',
    interviews: [
      {
        id: 'int-2',
        candidateId: 'cand-2',
        candidateName: 'Maya Chen',
        jobTitle: 'Frontend Developer',
        interviewerId: 'user-manager',
        interviewerName: 'David Miller',
        stage: 'Hiring Manager Screen',
        date: '2024-05-23',
        time: '11:00 AM',
        durationMinutes: 45,
        meetingLink: 'https://meet.google.com/maya-interview',
        status: 'Scheduled',
      }
    ],
  },
  {
    id: 'cand-3',
    organizationId: 'org-1',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    phone: '+1 (555) 441-2390',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Uber',
    currentRole: 'Senior Backend Engineer',
    experienceYears: 6,
    stage: 'Selected',
    rating: 4.9,
    appliedDate: '2024-05-02',
    expectedSalary: '$165,000',
    noticePeriod: 'Immediate',
    resumeUrl: '#',
    notes: 'Completed technical rounds with highest score in system architecture.',
    location: 'New York, NY',
    source: 'Referral',
    skills: ['Golang', 'Node.js', 'Distributed Systems', 'PostgreSQL', 'Kafka'],
    education: 'B.Tech in Computer Science, Georgia Tech',
    recruiterName: 'Elena Rostova',
    priority: 'Urgent' as any,
    talentPool: false,
    status: 'Active',
    screeningScore: 96,
    screeningStatus: 'Passed',
    interviews: [
      {
        id: 'int-3',
        candidateId: 'cand-3',
        candidateName: 'James Wilson',
        jobTitle: 'Backend Developer (Node / Go)',
        interviewerId: 'user-manager',
        interviewerName: 'Alex Johnson',
        stage: 'Final Architectural Review',
        date: '2024-05-18',
        time: '03:30 PM',
        durationMinutes: 60,
        meetingLink: 'https://meet.google.com/james-arch',
        status: 'Completed',
        score: 5,
        feedback: 'Superb answers on high concurrency and sharding.',
      }
    ],
  },
  {
    id: 'cand-4',
    organizationId: 'org-1',
    jobId: 'job-3',
    jobTitle: 'UI/UX Product Designer',
    name: 'Sophia Reynolds',
    email: 'sophia.r@designstudio.com',
    phone: '+1 (555) 883-9901',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Figma Community Creator',
    currentRole: 'Lead Product Designer',
    experienceYears: 4,
    stage: 'Shortlisted',
    rating: 4.2,
    appliedDate: '2024-05-14',
    expectedSalary: '$125,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Gorgeous portfolio of SaaS dashboards and micro-interactions.',
    location: 'Austin, TX',
    source: 'Job Portal',
    skills: ['Figma', 'Prototyping', 'Design Systems', 'User Research', 'Motion UI'],
    education: 'B.F.A. in Interactive Media, Rhode Island School of Design',
    recruiterName: 'Elena Rostova',
    priority: 'Medium',
    talentPool: false,
    status: 'Active',
    screeningScore: 85,
    screeningStatus: 'Passed',
    interviews: [],
  },
  {
    id: 'cand-5',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Liam Vance',
    email: 'liam.vance@techcorp.io',
    phone: '+1 (555) 234-8901',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Atlassian',
    currentRole: 'Senior Software Engineer',
    experienceYears: 5,
    stage: 'Offer Accepted',
    rating: 4.9,
    appliedDate: '2024-04-18',
    expectedSalary: '$140,000',
    noticePeriod: 'Completed',
    resumeUrl: '#',
    notes: 'Accepted offer letter. Joining date confirmed for June 1st.',
    location: 'San Francisco, CA',
    source: 'LinkedIn',
    skills: ['React', 'TypeScript', 'WebSockets', 'Tailwind CSS', 'Microfrontends'],
    education: 'B.S. in Computer Science, Stanford University',
    recruiterName: 'Elena Rostova',
    priority: 'High',
    talentPool: false,
    status: 'Active',
    screeningScore: 94,
    screeningStatus: 'Passed',
    interviews: [],
  },
  {
    id: 'cand-6',
    organizationId: 'org-1',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    name: 'Chloe Moreau',
    email: 'chloe.moreau@cloudnative.fr',
    phone: '+1 (555) 789-0124',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Datadog',
    currentRole: 'Cloud Infrastructure Dev',
    experienceYears: 6,
    stage: 'Offer',
    rating: 4.7,
    appliedDate: '2024-04-28',
    expectedSalary: '$160,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Formal offer sent at $160k. Pending signed acceptance.',
    location: 'Remote, US/EU',
    source: 'Referral',
    skills: ['Go', 'Kubernetes', 'Prometheus', 'gRPC', 'PostgreSQL'],
    education: 'M.S. in Computer Science, Sorbonne University',
    recruiterName: 'Elena Rostova',
    priority: 'High',
    talentPool: false,
    status: 'Active',
    screeningScore: 91,
    screeningStatus: 'Passed',
    interviews: [],
  },
  {
    id: 'cand-7',
    organizationId: 'org-1',
    jobId: 'job-3',
    jobTitle: 'UI/UX Product Designer',
    name: 'Marcus Brody',
    email: 'marcus.brody@designlab.com',
    phone: '+1 (555) 901-2345',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Airbnb',
    currentRole: 'UX Researcher & Designer',
    experienceYears: 7,
    stage: 'Joining',
    rating: 4.8,
    appliedDate: '2024-04-12',
    expectedSalary: '$135,000',
    noticePeriod: 'Serving Notice',
    resumeUrl: '#',
    notes: 'Background check cleared, IT laptop provisioned. Ready for onboarding.',
    location: 'San Francisco HQ',
    source: 'Career Page',
    skills: ['UX Research', 'Design Systems', 'Figma', 'Usability Testing'],
    education: 'B.A. in Cognitive Science, UC San Diego',
    recruiterName: 'Elena Rostova',
    priority: 'High',
    talentPool: false,
    status: 'Active',
    screeningScore: 90,
    screeningStatus: 'Passed',
    interviews: [],
  },
  {
    id: 'cand-8',
    organizationId: 'org-1',
    jobId: 'job-4',
    jobTitle: 'HR Executive',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@peopleops.in',
    phone: '+1 (555) 345-6789',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Freshworks',
    currentRole: 'HR Associate',
    experienceYears: 3,
    stage: 'Hired',
    rating: 4.6,
    appliedDate: '2024-03-25',
    expectedSalary: '$85,000',
    noticePeriod: 'Joined',
    resumeUrl: '#',
    notes: 'Handover complete. Currently in week 2 of HR induction program.',
    location: 'San Francisco HQ',
    source: 'LinkedIn',
    skills: ['HR Operations', 'HRIS Systems', 'Employee Engagement', 'Payroll Basics'],
    education: 'MBA in Human Resources, XLRI',
    recruiterName: 'Elena Rostova',
    priority: 'Medium',
    talentPool: false,
    status: 'Hired',
    screeningScore: 89,
    screeningStatus: 'Passed',
    interviews: [],
  },
  {
    id: 'cand-9',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Kevin Zhao',
    email: 'kevin.zhao@webstack.org',
    phone: '+1 (555) 456-7892',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Freelance',
    currentRole: 'Fullstack Contractor',
    experienceYears: 2,
    stage: 'Screening',
    rating: 3.8,
    appliedDate: '2024-05-16',
    expectedSalary: '$110,000',
    noticePeriod: 'Immediate',
    resumeUrl: '#',
    notes: 'Solid CSS skills, evaluating JS fundamentals in initial screening.',
    location: 'Seattle, WA',
    source: 'Direct',
    skills: ['JavaScript', 'HTML5/CSS3', 'Vue.js', 'Tailwind CSS'],
    education: 'B.S. in Information Tech, University of Oregon',
    recruiterName: 'Elena Rostova',
    priority: 'Low',
    talentPool: false,
    status: 'Active',
    screeningScore: 74,
    screeningStatus: 'Pending',
    interviews: [],
  },
  {
    id: 'cand-10',
    organizationId: 'org-1',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    name: 'Tariq Al-Mansoor',
    email: 'tariq.mansoor@devops.ae',
    phone: '+1 (555) 567-8903',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Careem',
    currentRole: 'Backend Engineer',
    experienceYears: 4,
    stage: 'Applied',
    rating: 4.1,
    appliedDate: '2024-05-17',
    expectedSalary: '$140,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Recent applicant with strong Node.js and Redis experience. Pending resume screening.',
    location: 'Remote',
    source: 'LinkedIn',
    skills: ['Node.js', 'Express', 'Redis', 'Docker', 'MongoDB'],
    education: 'B.S. in Software Engineering, AUS',
    recruiterName: 'Elena Rostova',
    priority: 'Medium',
    talentPool: false,
    status: 'Active',
    screeningScore: 82,
    screeningStatus: 'Pending',
    interviews: [],
  },
  {
    id: 'cand-11',
    organizationId: 'org-1',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    name: 'Emily Watson',
    email: 'emily.watson@agency.co',
    phone: '+1 (555) 678-9014',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Digital Agency Inc',
    currentRole: 'Web Developer',
    experienceYears: 3,
    stage: 'Rejected',
    rating: 2.8,
    appliedDate: '2024-05-04',
    expectedSalary: '$120,000',
    noticePeriod: '30 Days',
    resumeUrl: '#',
    notes: 'Did not meet core state-management requirements for senior tier.',
    location: 'Chicago, IL',
    source: 'Agency',
    skills: ['WordPress', 'Basic React', 'jQuery', 'CSS'],
    education: 'B.A. in Graphic Communication, DePaul University',
    recruiterName: 'Elena Rostova',
    priority: 'Low',
    talentPool: false,
    status: 'Rejected',
    screeningScore: 58,
    screeningStatus: 'Failed',
    interviews: [],
  },
  {
    id: 'cand-12',
    organizationId: 'org-1',
    jobId: 'job-3',
    jobTitle: 'UI/UX Product Designer',
    name: 'Julian Thorne',
    email: 'julian.t@interaction.io',
    phone: '+1 (555) 789-0125',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    currentCompany: 'Notion Ambassador',
    currentRole: 'Product Designer',
    experienceYears: 5,
    stage: 'Screening',
    rating: 4.4,
    appliedDate: '2024-05-15',
    expectedSalary: '$130,000',
    noticePeriod: '15 Days',
    resumeUrl: '#',
    notes: 'High potential talent in design token architectures. Saved to Talent Pool.',
    location: 'Denver, CO',
    source: 'Career Page',
    skills: ['Design Tokens', 'Figma Variants', 'Complex Enterprise UX', 'HTML/CSS'],
    education: 'B.S. in Human-Computer Interaction, Carnegie Mellon',
    recruiterName: 'Elena Rostova',
    priority: 'High',
    talentPool: true,
    status: 'Active',
    screeningScore: 87,
    screeningStatus: 'Pending',
    interviews: [],
  }
];

export const INITIAL_GOALS: GoalOKR[] = [
  {
    id: 'goal-1',
    organizationId: 'org-1',
    title: 'Migrate Core Services to Microservices Architecture',
    description: 'Decompose monolith APIs into scalable microservices to achieve sub-100ms P99 latency.',
    ownerId: 'emp-1',
    ownerName: 'Rahul Sharma',
    ownerAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    startDate: '2024-04-01',
    dueDate: '2024-06-30',
    progress: 75,
    status: 'In Progress',
    category: 'Department',
    keyResults: [
      { id: 'kr-1', title: 'Containerize auth and billing services', target: 100, current: 100, unit: '%' },
      { id: 'kr-2', title: 'Implement gRPC inter-service communication', target: 100, current: 80, unit: '%' },
      { id: 'kr-3', title: 'Achieve P99 API response under 100ms', target: 100, current: 45, unit: '%' },
    ],
  },
  {
    id: 'goal-2',
    organizationId: 'org-1',
    title: 'Grow Organic SaaS Signups by 40%',
    description: 'Execute new content strategy, SEO optimization, and interactive demo landing page.',
    ownerId: 'emp-2',
    ownerName: 'Priya Singh',
    ownerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    startDate: '2024-04-01',
    dueDate: '2024-06-30',
    progress: 60,
    status: 'In Progress',
    category: 'Department',
    keyResults: [
      { id: 'kr-4', title: 'Publish 12 high-intent SEO articles', target: 12, current: 9, unit: 'articles' },
      { id: 'kr-5', title: 'Increase website monthly visitors to 50k', target: 50000, current: 38000, unit: 'visitors' },
      { id: 'kr-6', title: 'Generate 500 trial signups', target: 500, current: 310, unit: 'signups' },
    ],
  },
  {
    id: 'goal-3',
    organizationId: 'org-1',
    title: 'Automate Month-End Payroll Reconciliation',
    description: 'Integrate automated tax calculation engine and 1-click payslip generation.',
    ownerId: 'emp-3',
    ownerName: 'Amit Kumar',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    startDate: '2024-05-01',
    dueDate: '2024-06-15',
    progress: 90,
    status: 'In Progress',
    category: 'Department',
    keyResults: [
      { id: 'kr-7', title: 'Complete tax compliance schema update', target: 100, current: 100, unit: '%' },
      { id: 'kr-8', title: 'Reduce payroll turnaround from 3 days to 4 hours', target: 100, current: 80, unit: '%' },
    ],
  },
];

export const INITIAL_EXPENSES: ExpenseClaim[] = [
  {
    id: 'exp-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    category: 'Software',
    amount: 240,
    currency: 'USD',
    date: '2024-05-14',
    description: 'JetBrains All Products Pack annual developer license',
    project: 'Core Platform Engineering',
    status: 'Approved',
    approvedDate: '2024-05-15',
    approverName: 'Amit Verma',
  },
  {
    id: 'exp-2',
    organizationId: 'org-1',
    employeeId: 'emp-2',
    employeeName: 'Priya Singh',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Travel',
    amount: 1250,
    currency: 'USD',
    date: '2024-05-10',
    description: 'Flight and accommodation for SaaS Growth Summit Chicago',
    project: 'Q2 Marketing Campaigns',
    status: 'Reimbursed',
    approvedDate: '2024-05-12',
    approverName: 'Sarah Jenkins',
  },
  {
    id: 'exp-3',
    organizationId: 'org-1',
    employeeId: 'emp-5',
    employeeName: 'Sandeep Yadav',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    category: 'Meals',
    amount: 185,
    currency: 'USD',
    date: '2024-05-18',
    description: 'Client dinner with Enterprise Prospect procurement team',
    project: 'Enterprise Accounts',
    status: 'Pending',
    approverName: 'David Vance',
  },
];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast-1',
    organizationId: 'org-1',
    assetTag: 'AST-0941',
    name: 'Apple MacBook Pro 16" M3 Max (36GB/1TB)',
    category: 'Laptop',
    serialNumber: 'C02G8721MD6T',
    assignedToEmployeeId: 'emp-1',
    assignedToEmployeeName: 'Rahul Sharma',
    assignedDate: '2023-04-16',
    condition: 'Brand New',
    status: 'Assigned',
    purchaseDate: '2023-04-10',
    purchaseCost: 3499,
  },
  {
    id: 'ast-2',
    organizationId: 'org-1',
    assetTag: 'AST-0942',
    name: 'Dell UltraSharp 32" 4K Thunderbolt Monitor',
    category: 'Monitor',
    serialNumber: 'CN-0K7938-72872',
    assignedToEmployeeId: 'emp-1',
    assignedToEmployeeName: 'Rahul Sharma',
    assignedDate: '2023-04-16',
    condition: 'Good',
    status: 'Assigned',
    purchaseDate: '2023-04-10',
    purchaseCost: 899,
  },
  {
    id: 'ast-3',
    organizationId: 'org-1',
    assetTag: 'AST-0943',
    name: 'Apple MacBook Air 15" M2 (16GB/512GB)',
    category: 'Laptop',
    serialNumber: 'C02H9843MD7U',
    assignedToEmployeeId: 'emp-2',
    assignedToEmployeeName: 'Priya Singh',
    assignedDate: '2023-02-12',
    condition: 'Good',
    status: 'Assigned',
    purchaseDate: '2023-02-05',
    purchaseCost: 1499,
  },
  {
    id: 'ast-4',
    organizationId: 'org-1',
    assetTag: 'AST-0944',
    name: 'Logitech MX Master 3S Wireless Mouse',
    category: 'Accessory',
    serialNumber: 'LZ-889123-09',
    condition: 'Brand New',
    status: 'Available',
    purchaseDate: '2024-01-10',
    purchaseCost: 99,
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    title: 'Offer Letter - Senior Software Engineer',
    category: 'Offer Letter',
    fileType: 'PDF',
    fileSize: '1.8 MB',
    uploadedDate: '2023-04-15',
    status: 'Verified',
    downloadUrl: '#',
  },
  {
    id: 'doc-2',
    organizationId: 'org-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Sharma',
    title: 'National Identity Proof / Passport Scan',
    category: 'ID Proof',
    fileType: 'PDF',
    fileSize: '3.2 MB',
    uploadedDate: '2023-04-15',
    expiryDate: '2031-10-12',
    status: 'Verified',
    downloadUrl: '#',
  },
  {
    id: 'doc-3',
    organizationId: 'org-1',
    title: 'Acme Corp Employee Handbook 2024',
    category: 'Policy',
    fileType: 'PDF',
    fileSize: '4.5 MB',
    uploadedDate: '2024-01-01',
    status: 'Verified',
    downloadUrl: '#',
  },
  {
    id: 'doc-4',
    organizationId: 'org-1',
    title: 'Comprehensive Health Insurance Policy Schedule',
    category: 'Policy',
    fileType: 'PDF',
    fileSize: '2.1 MB',
    uploadedDate: '2024-01-01',
    expiryDate: '2024-12-31',
    status: 'Verified',
    downloadUrl: '#',
  },
];

export const INITIAL_TRAINING_COURSES: TrainingCourse[] = [
  {
    id: 'trn-1',
    organizationId: 'org-1',
    title: 'Advanced React 19 & Architecture Design',
    category: 'Technical',
    description: 'Master server components, custom hooks, micro-frontends, and performance optimization.',
    instructor: 'Dan Abramov & Team',
    durationHours: 16,
    totalEnrolled: 24,
    completedCount: 18,
    rating: 4.9,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&auto=format&fit=crop&q=80',
    status: 'Active',
    enrolledEmployees: [
      { employeeId: 'emp-1', employeeName: 'Rahul Sharma', progress: 100, status: 'Completed', score: 98, completedDate: '2024-04-10' },
      { employeeId: 'emp-6', employeeName: 'Sarah Connor', progress: 80, status: 'In Progress' },
    ],
  },
  {
    id: 'trn-2',
    organizationId: 'org-1',
    title: 'Enterprise Information Security & SOC2 Compliance',
    category: 'Compliance',
    description: 'Mandatory annual training covering zero-trust, data confidentiality, and incident protocols.',
    instructor: 'SecOps Team',
    durationHours: 4,
    totalEnrolled: 124,
    completedCount: 110,
    rating: 4.6,
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&auto=format&fit=crop&q=80',
    status: 'Active',
    enrolledEmployees: [
      { employeeId: 'emp-1', employeeName: 'Rahul Sharma', progress: 100, status: 'Completed', score: 100, completedDate: '2024-01-20' },
      { employeeId: 'emp-2', employeeName: 'Priya Singh', progress: 100, status: 'Completed', score: 95, completedDate: '2024-01-22' },
    ],
  },
  {
    id: 'trn-3',
    organizationId: 'org-1',
    title: 'High-Impact SaaS Product Management & Growth',
    category: 'Leadership',
    description: 'Frameworks for PLG product-led growth, cohort retention, and customer feedback loops.',
    instructor: 'Elena Rostova',
    durationHours: 12,
    totalEnrolled: 18,
    completedCount: 12,
    rating: 4.8,
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&auto=format&fit=crop&q=80',
    status: 'Active',
    enrolledEmployees: [
      { employeeId: 'emp-2', employeeName: 'Priya Singh', progress: 65, status: 'In Progress' },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-hr-admin',
    title: 'New Leave Request',
    message: 'Priya Singh applied for 3 days Casual Leave (May 21 - May 23).',
    type: 'leave',
    isRead: false,
    timestamp: '10 minutes ago',
    actionUrl: '/leave/requests',
  },
  {
    id: 'notif-2',
    userId: 'user-hr-admin',
    title: 'Interview Scheduled',
    message: 'Technical interview scheduled for Aarav Patel (Frontend Dev) on May 22 at 2:00 PM.',
    type: 'interview',
    isRead: false,
    timestamp: '1 hour ago',
    actionUrl: '/recruitment/interviews',
  },
  {
    id: 'notif-3',
    userId: 'user-hr-admin',
    title: 'Payroll Generated for May 2024',
    message: 'Monthly payroll draft for 124 employees is ready for review and disbursement.',
    type: 'payroll',
    isRead: true,
    timestamp: 'Yesterday at 5:30 PM',
    actionUrl: '/payroll',
  },
  {
    id: 'notif-4',
    userId: 'user-employee',
    title: 'Payslip Available',
    message: 'Your payslip for April 2024 has been generated and is available for download.',
    type: 'payroll',
    isRead: false,
    timestamp: '2 days ago',
    actionUrl: '/my-payroll',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    organizationId: 'org-1',
    userId: 'user-hr-admin',
    userName: 'Sneha Gupta',
    userRole: 'HR Admin',
    action: 'APPROVED_LEAVE',
    module: 'Leave Management',
    ipAddress: '192.168.1.104',
    timestamp: '2024-05-18 14:32:10',
    status: 'Success',
    details: 'Approved 2 days Sick Leave for Amit Kumar (EMP003)',
  },
  {
    id: 'log-2',
    organizationId: 'org-1',
    userId: 'user-payroll-admin',
    userName: 'Marcus Sterling',
    userRole: 'Payroll Admin',
    action: 'PROCESS_PAYROLL_BATCH',
    module: 'Payroll',
    ipAddress: '192.168.1.188',
    timestamp: '2024-05-18 11:15:00',
    status: 'Success',
    details: 'Calculated tax deductions and generated monthly batch for 124 employees',
  },
  {
    id: 'log-3',
    organizationId: 'org-1',
    userId: 'user-recruiter',
    userName: 'Elena Rostova',
    userRole: 'Recruiter',
    action: 'MOVE_CANDIDATE_STAGE',
    module: 'Recruitment ATS',
    ipAddress: '192.168.1.45',
    timestamp: '2024-05-17 16:45:22',
    status: 'Success',
    details: 'Moved candidate Aarav Patel from Shortlisted to Technical Round',
  },
];

// =========================================================================
// RECRUITMENT & TALENT ACQUISITION SEED COLLECTIONS
// =========================================================================

export const INITIAL_MANPOWER_REQUIREMENTS: ManpowerRequirement[] = [
  {
    id: 'MPR-2025-001',
    organizationId: 'org-1',
    department: 'Engineering',
    position: 'Senior Staff Frontend Architect',
    requiredHeadcount: 2,
    existingHeadcount: 8,
    requiredDate: '2025-06-30',
    priority: 'Urgent',
    requestedBy: 'David Miller',
    requestedByRole: 'Engineering Manager',
    approvalStatus: 'Approved',
    approvedBy: 'Alex Johnson (VP of Operations)',
    reason: 'Scaling multi-tenant architecture and migrating design tokens across client suites.',
    budgetAllocated: '$280,000 - $320,000 / year',
    notes: 'Prioritize candidates with strong distributed frontend microservice experience.',
    createdAt: '2025-04-10',
  },
  {
    id: 'MPR-2025-002',
    organizationId: 'org-1',
    department: 'Product & Design',
    position: 'Lead UX Researcher',
    requiredHeadcount: 1,
    existingHeadcount: 3,
    requiredDate: '2025-07-15',
    priority: 'High',
    requestedBy: 'Rachel Green',
    requestedByRole: 'Head of People & Culture',
    approvalStatus: 'Pending Approval',
    reason: 'Expansion of user research laboratory and customer empathy sessions.',
    budgetAllocated: '$110,000 - $135,000 / year',
    notes: 'Must have enterprise SaaS research portfolio.',
    createdAt: '2025-04-18',
  },
  {
    id: 'MPR-2025-003',
    organizationId: 'org-1',
    department: 'Sales & Growth',
    position: 'Enterprise Account Executive',
    requiredHeadcount: 3,
    existingHeadcount: 5,
    requiredDate: '2025-06-01',
    priority: 'High',
    requestedBy: 'Marcus Sterling',
    requestedByRole: 'Chief Revenue Officer',
    approvalStatus: 'Approved',
    approvedBy: 'Alexander Wright (CEO)',
    reason: 'Scaling East Coast enterprise outreach and outbound ARR expansion.',
    budgetAllocated: '$150,000 Base + OTE',
    notes: 'Candidates with 4+ years closing $100k+ ACV contracts.',
    createdAt: '2025-04-05',
  },
  {
    id: 'MPR-2025-004',
    organizationId: 'org-1',
    department: 'Customer Success',
    position: 'Technical Implementation Specialist',
    requiredHeadcount: 2,
    existingHeadcount: 4,
    requiredDate: '2025-08-01',
    priority: 'Medium',
    requestedBy: 'Sneha Gupta',
    requestedByRole: 'HR Director',
    approvalStatus: 'Pending Approval',
    reason: 'Handling high onboarding volume from newly signed Enterprise tier tenants.',
    budgetAllocated: '$90,000 - $115,000 / year',
    createdAt: '2025-05-02',
  },
  {
    id: 'MPR-2025-005',
    organizationId: 'org-1',
    department: 'Engineering',
    position: 'Site Reliability / DevOps Engineer',
    requiredHeadcount: 1,
    existingHeadcount: 2,
    requiredDate: '2025-06-15',
    priority: 'Urgent',
    requestedBy: 'David Miller',
    requestedByRole: 'Engineering Manager',
    approvalStatus: 'Approved',
    approvedBy: 'Alex Johnson (VP of Operations)',
    reason: 'Transitioning to multi-region AWS and Kubernetes zero-downtime deploy pipeline.',
    budgetAllocated: '$155,000 - $185,000 / year',
    createdAt: '2025-04-12',
  }
];

export const INITIAL_JOB_REQUISITIONS: JobRequisition[] = [
  {
    id: 'REQ-2025-101',
    organizationId: 'org-1',
    manpowerRequirementId: 'MPR-2025-001',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    location: 'San Francisco / Remote',
    employmentType: 'Full-time',
    positions: 3,
    priority: 'Urgent',
    requestedBy: 'David Miller',
    hiringManager: 'David Miller',
    recruiterName: 'Elena Rostova',
    approvalStatus: 'Approved',
    businessJustification: 'Critical path requirement for Q3 enterprise dashboard release.',
    requiredSkills: ['React 18', 'TypeScript', 'Tailwind CSS', 'Redux / Zustand', 'Jest'],
    experienceRequired: '3-5 years',
    salaryRange: '$120,000 - $150,000',
    targetJoiningDate: '2025-06-15',
    createdDate: '2025-04-15',
    deadline: '2025-06-01',
    approvalHistory: [
      { approver: 'David Miller', role: 'Engineering Manager', status: 'Approved', date: '2025-04-15', comment: 'Approved for posting' },
      { approver: 'Alex Johnson', role: 'VP Operations', status: 'Approved', date: '2025-04-16', comment: 'Budget cleared' },
      { approver: 'Alexander Wright', role: 'CEO', status: 'Approved', date: '2025-04-17', comment: 'Proceed with priority sourcing' },
    ],
    recruitmentProgress: { applications: 24, screened: 16, interviewing: 8, offered: 2, hired: 1 }
  },
  {
    id: 'REQ-2025-102',
    organizationId: 'org-1',
    manpowerRequirementId: 'MPR-2025-005',
    jobTitle: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    location: 'San Francisco HQ',
    employmentType: 'Full-time',
    positions: 2,
    priority: 'Urgent',
    requestedBy: 'David Miller',
    hiringManager: 'Amit Verma',
    recruiterName: 'Elena Rostova',
    approvalStatus: 'Approved',
    businessJustification: 'Backfill and scaling high throughput microservices infrastructure.',
    requiredSkills: ['Go', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
    experienceRequired: '4-7 years',
    salaryRange: '$140,000 - $175,000',
    targetJoiningDate: '2025-07-01',
    createdDate: '2025-04-20',
    deadline: '2025-06-15',
    approvalHistory: [
      { approver: 'Amit Verma', role: 'Lead Architect', status: 'Approved', date: '2025-04-20' },
      { approver: 'Alex Johnson', role: 'VP Operations', status: 'Approved', date: '2025-04-21' },
    ],
    recruitmentProgress: { applications: 38, screened: 22, interviewing: 6, offered: 1, hired: 0 }
  },
  {
    id: 'REQ-2025-103',
    organizationId: 'org-1',
    jobTitle: 'UI/UX Product Designer',
    department: 'Design',
    location: 'Remote',
    employmentType: 'Full-time',
    positions: 1,
    priority: 'High',
    requestedBy: 'Rachel Green',
    hiringManager: 'Rachel Green',
    recruiterName: 'Elena Rostova',
    approvalStatus: 'Approved',
    businessJustification: 'Own end-to-end recruiter and employee dashboard design systems.',
    requiredSkills: ['Figma', 'Design Systems', 'Micro-interactions', 'User Research'],
    experienceRequired: '3-6 years',
    salaryRange: '$110,000 - $140,000',
    targetJoiningDate: '2025-06-30',
    createdDate: '2025-05-01',
    deadline: '2025-06-20',
    approvalHistory: [
      { approver: 'Rachel Green', role: 'Design Director', status: 'Approved', date: '2025-05-01' }
    ],
    recruitmentProgress: { applications: 16, screened: 10, interviewing: 4, offered: 0, hired: 0 }
  },
  {
    id: 'REQ-2025-104',
    organizationId: 'org-1',
    jobTitle: 'HR Executive',
    department: 'Human Resources',
    location: 'San Francisco HQ',
    employmentType: 'Full-time',
    positions: 1,
    priority: 'Medium',
    requestedBy: 'Sneha Gupta',
    hiringManager: 'Sneha Gupta',
    recruiterName: 'Elena Rostova',
    approvalStatus: 'Closed',
    businessJustification: 'Handle onboarding documentation and daily attendance operations.',
    requiredSkills: ['HR Operations', 'Compliance', 'Communication', 'HRIS tools'],
    experienceRequired: '2-4 years',
    salaryRange: '$75,000 - $95,000',
    targetJoiningDate: '2025-05-15',
    createdDate: '2025-03-20',
    deadline: '2025-05-01',
    approvalHistory: [
      { approver: 'Sneha Gupta', role: 'HR Director', status: 'Approved', date: '2025-03-20' }
    ],
    recruitmentProgress: { applications: 12, screened: 8, interviewing: 3, offered: 1, hired: 1 }
  },
  {
    id: 'REQ-2025-105',
    organizationId: 'org-1',
    manpowerRequirementId: 'MPR-2025-002',
    jobTitle: 'Lead UX Researcher',
    department: 'Product & Design',
    location: 'Remote',
    employmentType: 'Full-time',
    positions: 1,
    priority: 'High',
    requestedBy: 'Rachel Green',
    hiringManager: 'Rachel Green',
    recruiterName: 'Elena Rostova',
    approvalStatus: 'Pending Approval',
    businessJustification: 'Customer discovery for AI-assisted talent matching feature.',
    requiredSkills: ['Qualitative & Quantitative Research', 'Figma', 'Usability Lab'],
    experienceRequired: '5+ years',
    salaryRange: '$125,000 - $155,000',
    targetJoiningDate: '2025-07-15',
    createdDate: '2025-05-10',
    deadline: '2025-06-30',
    approvalHistory: [
      { approver: 'Rachel Green', role: 'Head of People', status: 'Approved', date: '2025-05-10' },
      { approver: 'Alex Johnson', role: 'VP Operations', status: 'Pending' }
    ],
    recruitmentProgress: { applications: 0, screened: 0, interviewing: 0, offered: 0, hired: 0 }
  }
];

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: 'APP-2025-001',
    organizationId: 'org-1',
    candidateId: 'cand-1',
    candidateName: 'Aarav Patel',
    candidateEmail: 'aarav.patel@email.com',
    candidatePhone: '+1 (555) 782-3344',
    candidateAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    appliedDate: '2024-05-08',
    source: 'LinkedIn',
    currentStage: 'Technical Round',
    recruiterName: 'Elena Rostova',
    experienceYears: 4,
    currentCompany: 'Stripe',
    resumeUrl: '#',
    resumeFileName: 'Aarav_Patel_Frontend_Staff.pdf',
    status: 'Active',
    rating: 4.8,
    notesCount: 3,
    interviewsCount: 2,
    timeline: [
      { stage: 'Applied', date: '2024-05-08', updatedBy: 'System', comment: 'Application submitted via LinkedIn Job Board' },
      { stage: 'Screening', date: '2024-05-09', updatedBy: 'Elena Rostova', comment: 'Screened - score 92/100' },
      { stage: 'Shortlisted', date: '2024-05-10', updatedBy: 'Elena Rostova', comment: 'Passed to engineering panelists' },
      { stage: 'Technical Round', date: '2024-05-15', updatedBy: 'Amit Verma', comment: 'Scheduled live system design round' },
    ]
  },
  {
    id: 'APP-2025-002',
    organizationId: 'org-1',
    candidateId: 'cand-2',
    candidateName: 'Maya Chen',
    candidateEmail: 'maya.chen@email.com',
    candidatePhone: '+1 (555) 621-8899',
    candidateAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    appliedDate: '2024-05-11',
    source: 'Career Page',
    currentStage: 'Interview',
    recruiterName: 'Elena Rostova',
    experienceYears: 5,
    currentCompany: 'Shopify',
    resumeUrl: '#',
    resumeFileName: 'Maya_Chen_UI_Lead.pdf',
    status: 'Active',
    rating: 4.5,
    notesCount: 2,
    interviewsCount: 1,
    timeline: [
      { stage: 'Applied', date: '2024-05-11', updatedBy: 'System' },
      { stage: 'Screening', date: '2024-05-12', updatedBy: 'Elena Rostova' },
      { stage: 'Interview', date: '2024-05-16', updatedBy: 'David Miller', comment: 'Interview scheduled with Engineering Manager' }
    ]
  },
  {
    id: 'APP-2025-003',
    organizationId: 'org-1',
    candidateId: 'cand-3',
    candidateName: 'James Wilson',
    candidateEmail: 'james.wilson@email.com',
    candidatePhone: '+1 (555) 441-2390',
    candidateAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    appliedDate: '2024-05-02',
    source: 'Referral',
    currentStage: 'Selected',
    recruiterName: 'Elena Rostova',
    experienceYears: 6,
    currentCompany: 'Uber',
    resumeUrl: '#',
    resumeFileName: 'James_Wilson_Distributed_Backend.pdf',
    status: 'Active',
    rating: 4.9,
    notesCount: 4,
    interviewsCount: 3,
    timeline: [
      { stage: 'Applied', date: '2024-05-02', updatedBy: 'System' },
      { stage: 'Screening', date: '2024-05-03', updatedBy: 'Elena Rostova' },
      { stage: 'Interview', date: '2024-05-08', updatedBy: 'Alex Johnson' },
      { stage: 'Selected', date: '2024-05-18', updatedBy: 'Elena Rostova', comment: 'Panel unanimous Strong Hire. Offer prep underway.' }
    ]
  },
  {
    id: 'APP-2025-004',
    organizationId: 'org-1',
    candidateId: 'cand-5',
    candidateName: 'Liam Vance',
    candidateEmail: 'liam.vance@techcorp.io',
    candidatePhone: '+1 (555) 234-8901',
    candidateAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    appliedDate: '2024-04-18',
    source: 'LinkedIn',
    currentStage: 'Offer Accepted',
    recruiterName: 'Elena Rostova',
    experienceYears: 5,
    currentCompany: 'Atlassian',
    resumeUrl: '#',
    resumeFileName: 'Liam_Vance_Staff_Engineer.pdf',
    status: 'Active',
    rating: 4.9,
    notesCount: 5,
    interviewsCount: 3,
    timeline: [
      { stage: 'Applied', date: '2024-04-18', updatedBy: 'System' },
      { stage: 'Interview', date: '2024-04-26', updatedBy: 'Amit Verma' },
      { stage: 'Offer', date: '2024-05-05', updatedBy: 'Elena Rostova' },
      { stage: 'Offer Accepted', date: '2024-05-12', updatedBy: 'Candidate', comment: 'Candidate signed digital offer letter.' }
    ]
  },
  {
    id: 'APP-2025-005',
    organizationId: 'org-1',
    candidateId: 'cand-6',
    candidateName: 'Chloe Moreau',
    candidateEmail: 'chloe.moreau@cloudnative.fr',
    candidatePhone: '+1 (555) 789-0124',
    candidateAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    appliedDate: '2024-04-28',
    source: 'Referral',
    currentStage: 'Offer',
    recruiterName: 'Elena Rostova',
    experienceYears: 6,
    currentCompany: 'Datadog',
    resumeUrl: '#',
    resumeFileName: 'Chloe_Moreau_Go_Cloud.pdf',
    status: 'Active',
    rating: 4.7,
    notesCount: 3,
    interviewsCount: 2,
    timeline: [
      { stage: 'Applied', date: '2024-04-28', updatedBy: 'System' },
      { stage: 'Interview', date: '2024-05-06', updatedBy: 'David Miller' },
      { stage: 'Offer', date: '2024-05-14', updatedBy: 'Elena Rostova', comment: 'Official offer sent with equity option' }
    ]
  },
  {
    id: 'APP-2025-006',
    organizationId: 'org-1',
    candidateId: 'cand-7',
    candidateName: 'Marcus Brody',
    candidateEmail: 'marcus.brody@designlab.com',
    candidatePhone: '+1 (555) 901-2345',
    candidateAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-3',
    jobTitle: 'UI/UX Product Designer',
    department: 'Design',
    appliedDate: '2024-04-12',
    source: 'Career Page',
    currentStage: 'Joining',
    recruiterName: 'Elena Rostova',
    experienceYears: 7,
    currentCompany: 'Airbnb',
    resumeUrl: '#',
    resumeFileName: 'Marcus_Brody_Principal_Design.pdf',
    status: 'Active',
    rating: 4.8,
    notesCount: 6,
    interviewsCount: 3,
    timeline: [
      { stage: 'Applied', date: '2024-04-12', updatedBy: 'System' },
      { stage: 'Offer Accepted', date: '2024-05-02', updatedBy: 'Candidate' },
      { stage: 'Joining', date: '2024-05-15', updatedBy: 'Elena Rostova', comment: 'Pre-handover checklist complete' }
    ]
  },
  {
    id: 'APP-2025-007',
    organizationId: 'org-1',
    candidateId: 'cand-10',
    candidateName: 'Tariq Al-Mansoor',
    candidateEmail: 'tariq.mansoor@devops.ae',
    candidatePhone: '+1 (555) 567-8903',
    candidateAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    appliedDate: '2024-05-17',
    source: 'LinkedIn',
    currentStage: 'Applied',
    recruiterName: 'Elena Rostova',
    experienceYears: 4,
    currentCompany: 'Careem',
    resumeUrl: '#',
    resumeFileName: 'Tariq_Mansoor_Backend.pdf',
    status: 'Active',
    rating: 4.1,
    notesCount: 1,
    interviewsCount: 0,
    timeline: [
      { stage: 'Applied', date: '2024-05-17', updatedBy: 'System', comment: 'Direct web application submitted' }
    ]
  }
];

export const INITIAL_RESUMES: ResumeDocument[] = [
  {
    id: 'RES-001',
    organizationId: 'org-1',
    candidateId: 'cand-1',
    candidateName: 'Aarav Patel',
    candidateEmail: 'aarav.patel@email.com',
    candidateAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    jobApplied: 'Frontend Developer',
    fileName: 'Aarav_Patel_Frontend_Staff.pdf',
    fileSize: '1.4 MB',
    uploadDate: '2024-05-08',
    resumeStatus: 'Verified',
    screeningStatus: 'Shortlisted',
    extractedSkills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux', 'Jest', 'Webpack'],
    extractedExperience: '4 Years at Stripe & Razorpay',
    extractedEducation: 'B.S. in Computer Science, UC Berkeley (GPA: 3.8)',
    matchScore: 94,
    downloadUrl: '#'
  },
  {
    id: 'RES-002',
    organizationId: 'org-1',
    candidateId: 'cand-2',
    candidateName: 'Maya Chen',
    candidateEmail: 'maya.chen@email.com',
    candidateAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    jobApplied: 'Frontend Developer',
    fileName: 'Maya_Chen_UI_Lead.pdf',
    fileSize: '980 KB',
    uploadDate: '2024-05-11',
    resumeStatus: 'Parsed',
    screeningStatus: 'Shortlisted',
    extractedSkills: ['React', 'Accessibility', 'Design Systems', 'GraphQL', 'Tailwind CSS'],
    extractedExperience: '5 Years at Shopify & Squarespace',
    extractedEducation: 'M.S. in Software Engineering, Univ. Washington',
    matchScore: 89,
    downloadUrl: '#'
  },
  {
    id: 'RES-003',
    organizationId: 'org-1',
    candidateId: 'cand-3',
    candidateName: 'James Wilson',
    candidateEmail: 'james.wilson@email.com',
    candidateAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    jobApplied: 'Backend Developer (Node / Go)',
    fileName: 'James_Wilson_Distributed_Backend.pdf',
    fileSize: '2.1 MB',
    uploadDate: '2024-05-02',
    resumeStatus: 'Verified',
    screeningStatus: 'Shortlisted',
    extractedSkills: ['Golang', 'Node.js', 'PostgreSQL', 'Kafka', 'Docker', 'Kubernetes'],
    extractedExperience: '6 Years at Uber & Twilio',
    extractedEducation: 'B.Tech in CS, Georgia Tech',
    matchScore: 98,
    downloadUrl: '#'
  },
  {
    id: 'RES-004',
    organizationId: 'org-1',
    candidateId: 'cand-4',
    candidateName: 'Sophia Reynolds',
    candidateEmail: 'sophia.r@designstudio.com',
    candidateAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    jobApplied: 'UI/UX Product Designer',
    fileName: 'Sophia_Reynolds_Portfolio_CV.pdf',
    fileSize: '4.8 MB',
    uploadDate: '2024-05-14',
    resumeStatus: 'Parsed',
    screeningStatus: 'Shortlisted',
    extractedSkills: ['Figma', 'Prototyping', 'Design Systems', 'User Research', 'Motion UI'],
    extractedExperience: '4 Years at Freelance Design Lab',
    extractedEducation: 'B.F.A. in Interactive Media, RISD',
    matchScore: 86,
    downloadUrl: '#'
  },
  {
    id: 'RES-005',
    organizationId: 'org-1',
    candidateId: 'cand-9',
    candidateName: 'Kevin Zhao',
    candidateEmail: 'kevin.zhao@webstack.org',
    candidateAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    jobApplied: 'Frontend Developer',
    fileName: 'Kevin_Zhao_Junior_Frontend.pdf',
    fileSize: '820 KB',
    uploadDate: '2024-05-16',
    resumeStatus: 'Pending',
    screeningStatus: 'Pending',
    extractedSkills: ['JavaScript', 'HTML5', 'CSS3', 'Vue.js', 'Bootstrap'],
    extractedExperience: '2 Years Contract Dev',
    extractedEducation: 'B.S. in IT, Univ. Oregon',
    matchScore: 72,
    downloadUrl: '#'
  },
  {
    id: 'RES-006',
    organizationId: 'org-1',
    candidateId: 'cand-11',
    candidateName: 'Emily Watson',
    candidateEmail: 'emily.watson@agency.co',
    candidateAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    jobApplied: 'Frontend Developer',
    fileName: 'Emily_Watson_WebDev.pdf',
    fileSize: '650 KB',
    uploadDate: '2024-05-04',
    resumeStatus: 'Verified',
    screeningStatus: 'Rejected',
    extractedSkills: ['WordPress', 'jQuery', 'Basic React', 'CSS'],
    extractedExperience: '3 Years at Agency',
    extractedEducation: 'B.A. Graphic Comm, DePaul',
    matchScore: 56,
    downloadUrl: '#'
  }
];

export const INITIAL_EVALUATIONS: InterviewEvaluation[] = [
  {
    id: 'EVAL-001',
    organizationId: 'org-1',
    candidateId: 'cand-1',
    candidateName: 'Aarav Patel',
    candidateAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Frontend Developer',
    interviewId: 'int-1',
    interviewRound: 'Technical Coding Round',
    interviewerId: 'user-manager',
    interviewerName: 'Amit Verma',
    interviewerRole: 'Lead Architect',
    evaluationDate: '2024-05-20',
    status: 'Completed',
    scores: {
      technicalSkills: 5,
      communication: 4,
      problemSolving: 5,
      experience: 4,
      cultureFit: 5
    },
    overallRating: 4.8,
    strengths: ['Flawless deep understanding of React concurrent rendering', 'Superb state management breakdown', 'Clean modular code structure'],
    weaknesses: ['Has primarily focused on web, minimal mobile React Native familiarity (not required for this role)'],
    comments: 'Aarav is one of the top frontend engineers interviewed this quarter. Highly recommended for final manager round.',
    recommendation: 'Strong Hire'
  },
  {
    id: 'EVAL-002',
    organizationId: 'org-1',
    candidateId: 'cand-3',
    candidateName: 'James Wilson',
    candidateAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Backend Developer (Node / Go)',
    interviewId: 'int-3',
    interviewRound: 'Final Architectural Review',
    interviewerId: 'user-org-admin',
    interviewerName: 'Alex Johnson',
    interviewerRole: 'VP Operations',
    evaluationDate: '2024-05-18',
    status: 'Completed',
    scores: {
      technicalSkills: 5,
      communication: 5,
      problemSolving: 5,
      experience: 5,
      cultureFit: 4
    },
    overallRating: 4.9,
    strengths: ['Exceptional distributed systems experience at scale', 'Calm and precise under high pressure scenarios', 'Great mentor mindset'],
    weaknesses: ['High compensation expectation ($165k), well justified given pedigree'],
    comments: 'Clear Strong Hire. Immediate asset to our backend infrastructure initiatives.',
    recommendation: 'Strong Hire'
  },
  {
    id: 'EVAL-003',
    organizationId: 'org-1',
    candidateId: 'cand-2',
    candidateName: 'Maya Chen',
    candidateAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Frontend Developer',
    interviewId: 'int-2',
    interviewRound: 'Hiring Manager Screen',
    interviewerId: 'user-manager',
    interviewerName: 'David Miller',
    interviewerRole: 'Engineering Manager',
    evaluationDate: '2024-05-23',
    status: 'Pending',
    scores: {
      technicalSkills: 0,
      communication: 0,
      problemSolving: 0,
      experience: 0,
      cultureFit: 0
    },
    overallRating: 0,
    strengths: [],
    weaknesses: [],
    comments: 'Evaluation pending scheduled interview on May 23rd at 11:00 AM.',
    recommendation: 'Hold'
  }
];

export const INITIAL_OFFERS: JobOffer[] = [
  {
    id: 'OFF-2025-01',
    organizationId: 'org-1',
    candidateId: 'cand-5',
    candidateName: 'Liam Vance',
    candidateEmail: 'liam.vance@techcorp.io',
    candidateAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-1',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    salaryAnnual: 140000,
    salaryFormatted: '$140,000 / year',
    joiningDate: '2025-06-01',
    employmentType: 'Full-time',
    offerStatus: 'Accepted',
    approvalStatus: 'Approved',
    approvedBy: 'Alexander Wright (CEO)',
    sentDate: '2025-05-06',
    responseDeadline: '2025-05-15',
    benefitsSummary: ['Comprehensive Health & Dental', '401(k) with 4% match', '$2,500 Home Office Stipend', 'Unlimited PTO'],
    notes: 'Candidate accepted on May 12th. Onboarding kit ordered.',
    createdAt: '2025-05-04'
  },
  {
    id: 'OFF-2025-02',
    organizationId: 'org-1',
    candidateId: 'cand-6',
    candidateName: 'Chloe Moreau',
    candidateEmail: 'chloe.moreau@cloudnative.fr',
    candidateAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    salaryAnnual: 160000,
    salaryFormatted: '$160,000 / year',
    joiningDate: '2025-06-15',
    employmentType: 'Full-time',
    offerStatus: 'Sent',
    approvalStatus: 'Approved',
    approvedBy: 'Alex Johnson (VP Operations)',
    sentDate: '2025-05-14',
    responseDeadline: '2025-05-24',
    benefitsSummary: ['Health & Life Insurance', 'Stock Options (0.05%)', 'Annual Tech Budget $3,000'],
    notes: 'Follow up scheduled for May 21st.',
    createdAt: '2025-05-12'
  },
  {
    id: 'OFF-2025-03',
    organizationId: 'org-1',
    candidateId: 'cand-3',
    candidateName: 'James Wilson',
    candidateEmail: 'james.wilson@email.com',
    candidateAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    jobId: 'job-2',
    jobTitle: 'Backend Developer (Node / Go)',
    department: 'Engineering',
    salaryAnnual: 165000,
    salaryFormatted: '$165,000 / year',
    joiningDate: '2025-06-15',
    employmentType: 'Full-time',
    offerStatus: 'Draft',
    approvalStatus: 'Pending',
    responseDeadline: '2025-05-30',
    benefitsSummary: ['Full Health & Dental', '401(k) 5% match', 'Flexible Hybrid Work'],
    notes: 'Draft awaiting HR Director sign-off before dispatching to candidate.',
    createdAt: '2025-05-19'
  }
];

export const INITIAL_HANDOVERS: OnboardingHandover[] = [
  {
    id: 'HND-2025-01',
    organizationId: 'org-1',
    candidateId: 'cand-7',
    applicantId: 'APP-2025-006',
    candidateName: 'Marcus Brody',
    candidateEmail: 'marcus.brody@designlab.com',
    candidatePhone: '+1 (555) 901-2345',
    candidateAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'UI/UX Product Designer',
    department: 'Design',
    designation: 'Lead Product Designer',
    joiningDate: '2025-06-01',
    offerStatus: 'Accepted',
    documentsStatus: 'Verified',
    handoverStatus: 'Ready for Handover',
    checklist: {
      offerAccepted: true,
      personalInfoComplete: true,
      resumeAvailable: true,
      documentsUploaded: true,
      joiningDateConfirmed: true,
      salaryDetailsApproved: true,
      jobConfirmed: true,
      jobDepartmentConfirmed: true
    },
    assignedHrName: 'Sneha Gupta',
    notes: 'All paperwork verified. Ready to initiate HR portal onboarding.'
  },
  {
    id: 'HND-2025-02',
    organizationId: 'org-1',
    candidateId: 'cand-5',
    applicantId: 'APP-2025-004',
    candidateName: 'Liam Vance',
    candidateEmail: 'liam.vance@techcorp.io',
    candidatePhone: '+1 (555) 234-8901',
    candidateAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    designation: 'Senior Frontend Engineer',
    joiningDate: '2025-06-01',
    offerStatus: 'Accepted',
    documentsStatus: 'Under Review',
    handoverStatus: 'Ready for Handover',
    checklist: {
      offerAccepted: true,
      personalInfoComplete: true,
      resumeAvailable: true,
      documentsUploaded: true,
      joiningDateConfirmed: true,
      salaryDetailsApproved: true,
      jobConfirmed: true,
      jobDepartmentConfirmed: true
    },
    assignedHrName: 'Priya Sharma',
    notes: 'Background verification report uploaded.'
  },
  {
    id: 'HND-2025-03',
    organizationId: 'org-1',
    candidateId: 'cand-8',
    applicantId: 'APP-2025-008',
    candidateName: 'Ananya Deshmukh',
    candidateEmail: 'ananya.d@peopleops.in',
    candidatePhone: '+1 (555) 345-6789',
    candidateAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'HR Executive',
    department: 'Human Resources',
    designation: 'HR Executive',
    joiningDate: '2025-05-15',
    offerStatus: 'Accepted',
    documentsStatus: 'Verified',
    handoverStatus: 'Completed',
    checklist: {
      offerAccepted: true,
      personalInfoComplete: true,
      resumeAvailable: true,
      documentsUploaded: true,
      joiningDateConfirmed: true,
      salaryDetailsApproved: true,
      jobConfirmed: true,
      jobDepartmentConfirmed: true
    },
    assignedHrName: 'Sneha Gupta',
    handoverDate: '2025-05-14',
    notes: 'Successfully enrolled into employee database (EMP-0144).'
  }
];

